//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libgermantok.dylib
// UUID: 81465334-97AD-3DF1-B8A9-231CEF069296
//
//                           Arch: arm64
//                 Source version: 18.0.0.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//

//
// This file does not contain any Objective-C runtime information.
//
