//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Security.framework/Versions/A/Security
// UUID: 8DC40063-F3D1-30C3-9184-CF7981E78574
//
//                           Arch: x86_64
//                 Source version: 57031.1.34.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.10.0
//

//
// This file does not contain any Objective-C runtime information.
//
