//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/IDEBundleInjection.framework/IDEBundleInjection
// UUID: 0648D99A-9F83-320E-AD7A-9B9899C3E54E
//
//                           Arch: arm64
//                Current version: 6746.0.0
//          Compatibility version: 1.0.0
//                 Source version: 6746.0.0.0.0
//            Minimum iOS version: 7.0.0
//                    SDK version: 8.2.0
//

//
// This file does not contain any Objective-C runtime information.
//
