//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/PrivateFrameworks/IOAccelerator.framework/IOAccelerator
// UUID: 473F8D64-5A6F-37A1-BD4D-899B1F17C249
//
//                           Arch: arm64
//                 Source version: 151.3.0.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//

//
// This file does not contain any Objective-C runtime information.
//
