//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/lib/libktrace.dylib
// UUID: 0F4AA813-FC7B-3C95-A54C-9D6CC6E56648
//
//                           Arch: x86_64
//                 Source version: 72.1.3.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.10.0
//

//
// This file does not contain any Objective-C runtime information.
//
