//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libGestureServer.dylib
// UUID: C670DD0D-4753-39A6-B755-C025AF3FF05D
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 3318.29.0.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (_Bool)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol NSXPCListenerDelegate <NSObject>

@optional
- (_Bool)listener:(NSXPCListener *)arg1 shouldAcceptNewConnection:(NSXPCConnection *)arg2;
@end

@protocol _UIGestureRecognizerServerInterface <NSObject>
- (void)ipc_requestGestureRecognizerInstructionForContextID:(unsigned int)arg1 withInitialTouchTimestamp:(double)arg2 reply:(void (^)(long long))arg3;
- (void)ipc_removeGestureRecognizerStateForContextId:(unsigned int)arg1 withInitialTouchTimestamp:(double)arg2;
- (void)ipc_setGestureRecognizerState:(long long)arg1 forGestureRecognizersInContextId:(unsigned int)arg2 affectingContextId:(unsigned int)arg3 withInitialTouchTimestamp:(double)arg4 lastTouchTimestamp:(double)arg5;
- (void)ipc_setGestureRecognizerState:(long long)arg1 forGestureRecognizersInContextId:(unsigned int)arg2 withInitialTouchTimestamp:(double)arg3 lastTouchTimestamp:(double)arg4;
@end

@interface _UIGestureRecognizerContextState : NSObject
{
    unsigned int _contextId;
    unsigned int _ancestorContextId;
    double _initialTouchTimestamp;
    double _lastTouchTimestamp;
    double _lastAncestorTouchTimestamp;
    long long _gestureRecognizerState;
    long long _ancestorGestureRecognizerState;
    _Bool _didReset;
    _Bool _ancestorDidReset;
}

@end

@interface _UIGestureRecognizerServer : NSObject <NSXPCListenerDelegate, _UIGestureRecognizerServerInterface>
{
    NSMutableSet *_contextReuseQueue;
    NSMapTable *_contextToStateMap;
    NSMutableDictionary *_handEventToHitContextsMap;
    NSXPCListener *_listener;
    NSObject<OS_dispatch_queue> *_handlerQueue;
}

+ (id)sharedServer;
- (void)_queue_touchesWithInitialTouchTimestamp:(double)arg1 wereDeliveredToContexts:(id)arg2;
- (void)touchesWithInitialTouchTimestamp:(double)arg1 wereDeliveredToContexts:(unsigned int *)arg2 count:(unsigned char)arg3;
- (void)ipc_requestGestureRecognizerInstructionForContextID:(unsigned int)arg1 withInitialTouchTimestamp:(double)arg2 reply:(CDUnknownBlockType)arg3;
- (long long)_queue_gestureRecognizersCanBeginGivenAncestorsOfContextId:(unsigned int)arg1 withInitialTouchTimestamp:(double)arg2;
- (long long)_queue_gestureRecognizersCanBeginGivenDescendantsOfContextId:(unsigned int)arg1 withInitialTouchTimestamp:(double)arg2 ancestorGestureRecognizerState:(long long)arg3 lastTouchTimestamp:(double)arg4;
- (void)_queue_removeGestureRecognizerStateForContextId:(unsigned int)arg1 withInitialTouchTimestamp:(double)arg2;
- (void)ipc_removeGestureRecognizerStateForContextId:(unsigned int)arg1 withInitialTouchTimestamp:(double)arg2;
- (void)ipc_setGestureRecognizerState:(long long)arg1 forGestureRecognizersInContextId:(unsigned int)arg2 affectingContextId:(unsigned int)arg3 withInitialTouchTimestamp:(double)arg4 lastTouchTimestamp:(double)arg5;
- (long long)_queue_touchDeliveryStateForContextId:(unsigned int)arg1 withInitialTouchTimestamp:(double)arg2;
- (void)ipc_setGestureRecognizerState:(long long)arg1 forGestureRecognizersInContextId:(unsigned int)arg2 withInitialTouchTimestamp:(double)arg3 lastTouchTimestamp:(double)arg4;
- (void)_queue_enumerateContextStatesWithBlock:(CDUnknownBlockType)arg1;
- (id)_queue_stateForContextId:(unsigned int)arg1 withInitialTouchTimestamp:(double)arg2 createIfMissing:(_Bool)arg3;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)run;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

