//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGSize {
    double width;
    double height;
};

struct _xmlDoc;

struct _xmlError {
    int _field1;
    int _field2;
    char *_field3;
    int _field4;
    char *_field5;
    int _field6;
    char *_field7;
    char *_field8;
    char *_field9;
    int _field10;
    int _field11;
    void *_field12;
    void *_field13;
};

struct _xmlHashTable;

struct _xmlNode;

struct _xmlParserCtxt {
    struct _xmlSAXHandler *_field1;
    void *_field2;
    struct _xmlDoc *_field3;
    int _field4;
    int _field5;
    char *_field6;
    char *_field7;
    int _field8;
    int _field9;
    struct _xmlParserInput *_field10;
    int _field11;
    int _field12;
    struct _xmlParserInput **_field13;
    struct _xmlNode *_field14;
    int _field15;
    int _field16;
    struct _xmlNode **_field17;
    int _field18;
    struct _xmlParserNodeInfoSeq {
        unsigned long long _field1;
        unsigned long long _field2;
        struct _xmlParserNodeInfo *_field3;
    } _field19;
    int _field20;
    int _field21;
    int _field22;
    int _field23;
    int _field24;
    int _field25;
    struct _xmlValidCtxt {
        void *_field1;
        CDUnknownFunctionPointerType _field2;
        CDUnknownFunctionPointerType _field3;
        struct _xmlNode *_field4;
        int _field5;
        int _field6;
        struct _xmlNode **_field7;
        unsigned int _field8;
        struct _xmlDoc *_field9;
        int _field10;
        struct _xmlValidState *_field11;
        int _field12;
        int _field13;
        struct _xmlValidState *_field14;
        struct _xmlAutomata *_field15;
        struct _xmlAutomataState *_field16;
    } _field26;
    int _field27;
    int _field28;
    char *_field29;
    char *_field30;
    int _field31;
    int _field32;
    char **_field33;
    long long _field34;
    long long _field35;
    int _field36;
    int _field37;
    int _field38;
    char *_field39;
    char *_field40;
    char *_field41;
    int *_field42;
    int _field43;
    int _field44;
    int *_field45;
    int _field46;
    struct _xmlParserInput *_field47;
    int _field48;
    int _field49;
    int _field50;
    int _field51;
    void *_field52;
    int _field53;
    int _field54;
    void *_field55;
    int _field56;
    int _field57;
    struct _xmlDict *_field58;
    char **_field59;
    int _field60;
    int _field61;
    char *_field62;
    char *_field63;
    char *_field64;
    int _field65;
    int _field66;
    int _field67;
    char **_field68;
    int *_field69;
    void **_field70;
    struct _xmlHashTable *_field71;
    struct _xmlHashTable *_field72;
    int _field73;
    int _field74;
    int _field75;
    int _field76;
    struct _xmlNode *_field77;
    int _field78;
    struct _xmlAttr *_field79;
    struct _xmlError _field80;
    int _field81;
    unsigned long long _field82;
    unsigned long long _field83;
    struct _xmlParserNodeInfo *_field84;
    int _field85;
    int _field86;
    struct _xmlParserNodeInfo *_field87;
    int _field88;
    unsigned long long _field89;
};

struct _xmlParserInput;

struct _xmlParserNodeInfo;

struct _xmlSAXHandler {
    CDUnknownFunctionPointerType internalSubset;
    CDUnknownFunctionPointerType isStandalone;
    CDUnknownFunctionPointerType hasInternalSubset;
    CDUnknownFunctionPointerType hasExternalSubset;
    CDUnknownFunctionPointerType resolveEntity;
    CDUnknownFunctionPointerType getEntity;
    CDUnknownFunctionPointerType entityDecl;
    CDUnknownFunctionPointerType notationDecl;
    CDUnknownFunctionPointerType attributeDecl;
    CDUnknownFunctionPointerType elementDecl;
    CDUnknownFunctionPointerType unparsedEntityDecl;
    CDUnknownFunctionPointerType setDocumentLocator;
    CDUnknownFunctionPointerType startDocument;
    CDUnknownFunctionPointerType endDocument;
    CDUnknownFunctionPointerType startElement;
    CDUnknownFunctionPointerType endElement;
    CDUnknownFunctionPointerType reference;
    CDUnknownFunctionPointerType characters;
    CDUnknownFunctionPointerType ignorableWhitespace;
    CDUnknownFunctionPointerType processingInstruction;
    CDUnknownFunctionPointerType comment;
    CDUnknownFunctionPointerType warning;
    CDUnknownFunctionPointerType error;
    CDUnknownFunctionPointerType fatalError;
    CDUnknownFunctionPointerType getParameterEntity;
    CDUnknownFunctionPointerType cdataBlock;
    CDUnknownFunctionPointerType externalSubset;
    unsigned int initialized;
    void *_private;
    CDUnknownFunctionPointerType startElementNs;
    CDUnknownFunctionPointerType endElementNs;
    CDUnknownFunctionPointerType serror;
};

struct _xmlValidState;

#pragma mark Typedef'd Structures

// Ambiguous groups
typedef struct {
    unsigned int fullSyncVersion:1;
} CDStruct_a125a100;

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/NanoMailKitServer.framework/NanoMailKitServer
// UUID: A5A0A9DE-DB84-3987-AD46-13C339B374D4
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 284.0.0.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol IDSServiceDelegate <NSObject>

@optional
- (void)serviceAllowedTrafficClassifiersDidReset:(IDSService *)arg1;
- (void)serviceSpaceDidBecomeAvailable:(IDSService *)arg1;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 inviteReceivedForSession:(IDSSession *)arg3 fromID:(NSString *)arg4 withContext:(NSData *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 inviteReceivedForSession:(IDSSession *)arg3 fromID:(NSString *)arg4 withOptions:(NSDictionary *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 inviteReceivedForSession:(IDSSession *)arg3 fromID:(NSString *)arg4;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 identifier:(NSString *)arg3 hasBeenDeliveredWithContext:(id)arg4;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 identifier:(NSString *)arg3 didSendWithSuccess:(_Bool)arg4 error:(NSError *)arg5;
- (void)service:(IDSService *)arg1 nearbyDevicesChanged:(NSArray *)arg2;
- (void)service:(IDSService *)arg1 devicesChanged:(NSArray *)arg2;
- (void)service:(IDSService *)arg1 activeAccountsChanged:(NSSet *)arg2;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingResourceAtURL:(NSURL *)arg3 metadata:(NSDictionary *)arg4 fromID:(NSString *)arg5 context:(IDSMessageContext *)arg6;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingResourceAtURL:(NSURL *)arg3 fromID:(NSString *)arg4 context:(IDSMessageContext *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingUnhandledProtobuf:(IDSProtobuf *)arg3 fromID:(NSString *)arg4 context:(IDSMessageContext *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingData:(NSData *)arg3 fromID:(NSString *)arg4 context:(IDSMessageContext *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingMessage:(NSDictionary *)arg3 fromID:(NSString *)arg4 context:(IDSMessageContext *)arg5;
@end

@protocol NNMKAccountsSyncServiceServerDelegate <NSObject>
- (void)accountsSyncServiceServer:(NNMKAccountsSyncServiceServer *)arg1 didSendProtobufSuccessfullyWithIDSIdentifier:(NSString *)arg2;
- (void)accountsSyncServiceServer:(NNMKAccountsSyncServiceServer *)arg1 didFailSendingProtobufWithIDSIdentifier:(NSString *)arg2 errorCode:(long long)arg3;
@end

@protocol NNMKFetchesSyncServiceServerDelegate <NSObject>
- (void)fetchesSyncServiceServer:(NNMKFetchesSyncServiceServer *)arg1 didNotifyInitialSyncFinished:(NNMKProtoInitialSyncFinishedNotification *)arg2;
- (void)fetchesSyncServiceServer:(NNMKFetchesSyncServiceServer *)arg1 didRequestFullSync:(NNMKProtoFullSyncRequest *)arg2;
- (void)fetchesSyncServiceServer:(NNMKFetchesSyncServiceServer *)arg1 didRequestContent:(NNMKProtoContentRequest *)arg2;
- (void)fetchesSyncServiceServer:(NNMKFetchesSyncServiceServer *)arg1 didRequestMoreMessagesForConversation:(NNMKProtoMoreMessagesForConversationRequest *)arg2;
- (void)fetchesSyncServiceServer:(NNMKFetchesSyncServiceServer *)arg1 didRequestMoreMessages:(NNMKProtoMoreMessagesRequest *)arg2;
- (void)fetchesSyncServiceServer:(NNMKFetchesSyncServiceServer *)arg1 didRequestFetch:(NNMKProtoFetchRequest *)arg2;
@end

@protocol NNMKMailboxItem <NSObject>
@property(nonatomic) unsigned long long status;
@property(retain, nonatomic) NSString *preview;
@property(retain, nonatomic) NSString *subject;
- (void)removeState:(unsigned long long)arg1;
- (void)addState:(unsigned long long)arg1;
- (_Bool)checkState:(unsigned long long)arg1;
@end

@protocol NNMKMessageContentSyncServiceServerDelegate <NSObject>
- (void)messageContentSyncServiceServer:(NNMKMessageContentSyncServiceServer *)arg1 didSendProtobufSuccessfullyWithIDSIdentifier:(NSString *)arg2;
- (void)messageContentSyncServiceServer:(NNMKMessageContentSyncServiceServer *)arg1 didFailSendingProtobufWithIDSIdentifier:(NSString *)arg2 errorCode:(long long)arg3;
@end

@protocol NNMKMessagesSyncServiceServerDelegate <NSObject>
- (void)messagesSyncServiceServer:(NNMKMessagesSyncServiceServer *)arg1 didRequestSendMessage:(NNMKProtoSendMessageRequest *)arg2;
- (void)messagesSyncServiceServer:(NNMKMessagesSyncServiceServer *)arg1 didRequestCompactMessages:(NNMKProtoCompactMessagesRequest *)arg2;
- (void)messagesSyncServiceServer:(NNMKMessagesSyncServiceServer *)arg1 didWarnMessagesFilteredOut:(NNMKProtoMessagesFilteredOutWarning *)arg2;
- (void)messagesSyncServiceServer:(NNMKMessagesSyncServiceServer *)arg1 didDeleteMessages:(NNMKProtoMessageDeletions *)arg2;
- (void)messagesSyncServiceServer:(NNMKMessagesSyncServiceServer *)arg1 didUpdateMessagesStatus:(NNMKProtoMessageStatusUpdates *)arg2;
- (void)messagesSyncServiceServer:(NNMKMessagesSyncServiceServer *)arg1 didSendProtobufSuccessfullyWithIDSIdentifier:(NSString *)arg2;
- (void)messagesSyncServiceServer:(NNMKMessagesSyncServiceServer *)arg1 didFailSendingProtobufWithIDSIdentifier:(NSString *)arg2 errorCode:(long long)arg3;
@end

@protocol NSCoding
- (id)initWithCoder:(NSCoder *)arg1;
- (void)encodeWithCoder:(NSCoder *)arg1;
@end

@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)arg1;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (_Bool)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol NSSecureCoding <NSCoding>
+ (_Bool)supportsSecureCoding;
@end

@protocol PSYSyncCoordinatorDelegate <NSObject>
- (void)syncCoordinatorDidReceiveStartSyncCommand:(PSYSyncCoordinator *)arg1;

@optional
- (void)syncCoordinatorDidChangeSyncRestriction:(PSYSyncCoordinator *)arg1;
@end

@interface NNMKProtoMoreMessagesForConversationRequest : PBRequest <NSCopying>
{
    NSData *_beforeDateReceived;
    NSString *_conversationId;
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(retain, nonatomic) NSData *beforeDateReceived; // @synthesize beforeDateReceived=_beforeDateReceived;
@property(retain, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasBeforeDateReceived;
@property(readonly, nonatomic) _Bool hasConversationId;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKProtoAccountDeletion : PBCodable <NSCopying>
{
    NSString *_accountId;
}

@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasAccountId;

@end

@interface NNMKProtoMessageStatusUpdate : PBCodable <NSCopying>
{
    NSString *_messageId;
    unsigned int _statusVersion;
    unsigned int _updatedStatus;
    struct {
        unsigned int statusVersion:1;
        unsigned int updatedStatus:1;
    } _has;
}

@property(nonatomic) unsigned int statusVersion; // @synthesize statusVersion=_statusVersion;
@property(nonatomic) unsigned int updatedStatus; // @synthesize updatedStatus=_updatedStatus;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasStatusVersion;
@property(nonatomic) _Bool hasUpdatedStatus;
@property(readonly, nonatomic) _Bool hasMessageId;

@end

@interface NNMKSyncEndpoint : NSObject
{
    NSObject<OS_dispatch_queue> *_endpointQueue;
    NSObject<OS_dispatch_queue> *_resendingQueue;
    NSMutableDictionary *_datesForIDSIdentifiersScheduledToBeResent;
    NSMutableDictionary *_lastResendIntervalKeyedByIDSIdentifier;
}

@property(retain, nonatomic) NSMutableDictionary *lastResendIntervalKeyedByIDSIdentifier; // @synthesize lastResendIntervalKeyedByIDSIdentifier=_lastResendIntervalKeyedByIDSIdentifier;
@property(retain, nonatomic) NSMutableDictionary *datesForIDSIdentifiersScheduledToBeResent; // @synthesize datesForIDSIdentifiersScheduledToBeResent=_datesForIDSIdentifiersScheduledToBeResent;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *resendingQueue; // @synthesize resendingQueue=_resendingQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *endpointQueue; // @synthesize endpointQueue=_endpointQueue;
- (void).cxx_destruct;
- (void)resendIDSIdentifier:(id)arg1;
- (void)dequeueIDSIdentifierForResend:(id)arg1;
- (unsigned long long)newResendIntervalForPreviousResendInterval:(unsigned long long)arg1 errorCode:(long long)arg2;
- (void)resendReadyIDSIdentifiers;
- (void)enqueueIDSIdentifierForResend:(id)arg1 atDate:(id)arg2 silent:(_Bool)arg3;
- (void)enqueueIDSIdentifiersForResend:(id)arg1;
- (id)initWithQueue:(id)arg1;

@end

@interface NNMKProtectedSQLiteConnection : NNMKSQLiteConnection
{
    _Bool _protectedDatabaseAttached;
    NSString *_protectedDatabasePath;
    NSString *_protectedDatabaseName;
}

@property(retain, nonatomic) NSString *protectedDatabaseName; // @synthesize protectedDatabaseName=_protectedDatabaseName;
@property(retain, nonatomic) NSString *protectedDatabasePath; // @synthesize protectedDatabasePath=_protectedDatabasePath;
@property(readonly, nonatomic) _Bool protectedDatabaseAttached; // @synthesize protectedDatabaseAttached=_protectedDatabaseAttached;
- (void).cxx_destruct;
- (id)_vfsModuleName;
- (void)dettachProtectedDatabase;
- (int)attachProtectedDatabase;
- (id)initWithUnprotectedDatabaseFileName:(id)arg1 protectedDatabaseFileName:(id)arg2 inDirectory:(id)arg3 protectedDatabaseName:(id)arg4 errorCode:(int *)arg5;

@end

@interface NNMKAccountsSyncServiceServer : NNMKSyncServiceEndpoint
{
    id <NNMKAccountsSyncServiceServerDelegate> _delegate;
}

@property(nonatomic) __weak id <NNMKAccountsSyncServiceServerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)readProtobufData:(id)arg1 type:(unsigned long long)arg2;
- (void)failedSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)successfullySentProtobufWithIDSIdentifier:(id)arg1;
- (id)sendInitialAccountsSync:(id)arg1;
- (id)deleteAccount:(id)arg1;
- (id)addOrUpdateAccount:(id)arg1;
- (id)initWithQueue:(id)arg1;

@end

@interface NNMKProtoSendMessageRequest : PBRequest <NSCopying>
{
    NSString *_body;
    NSMutableArray *_ccs;
    NSString *_subject;
    NSMutableArray *_tos;
}

@property(retain, nonatomic) NSString *body; // @synthesize body=_body;
@property(retain, nonatomic) NSString *subject; // @synthesize subject=_subject;
@property(retain, nonatomic) NSMutableArray *ccs; // @synthesize ccs=_ccs;
@property(retain, nonatomic) NSMutableArray *tos; // @synthesize tos=_tos;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasBody;
@property(readonly, nonatomic) _Bool hasSubject;
- (id)ccAtIndex:(unsigned long long)arg1;
- (unsigned long long)ccsCount;
- (void)addCc:(id)arg1;
- (void)clearCcs;
- (id)toAtIndex:(unsigned long long)arg1;
- (unsigned long long)tosCount;
- (void)addTo:(id)arg1;
- (void)clearTos;

@end

@interface NNMKPairedDeviceInfo : NSObject
{
    double _screenWidth;
    double _screenScale;
}

+ (id)pairedDeviceInfoWithScreenWidth:(double)arg1 screenScale:(double)arg2;
@property(nonatomic) double screenScale; // @synthesize screenScale=_screenScale;
@property(nonatomic) double screenWidth; // @synthesize screenWidth=_screenWidth;

@end

@interface NNMKLog : NSObject
{
}

+ (void)_setupLoggingFacility:(id)arg1;
+ (void)setupLoggingFacility:(id)arg1;
+ (void)setupLoggingFacilities;

@end

@interface NNMKFetchesSyncServiceClient : NNMKSyncServiceEndpoint
{
    id <NNMKFetchesSyncServiceClientDelegate> _delegate;
}

@property(nonatomic) __weak id <NNMKFetchesSyncServiceClientDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)readProtobufData:(id)arg1 type:(unsigned long long)arg2;
- (void)failedSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)successfullySentProtobufWithIDSIdentifier:(id)arg1;
- (id)notifyInitialSyncFinished:(id)arg1;
- (id)requestFullSync:(id)arg1;
- (void)requestContent:(id)arg1 highPriority:(_Bool)arg2;
- (void)requestMoreMessagesForConversation:(id)arg1;
- (id)requestMoreMessages:(id)arg1;
- (id)requestFetch:(id)arg1;
- (id)initWithQueue:(id)arg1;

@end

@interface NNMKHTMLParser : NSObject
{
    _Bool _isLastCharAddedLineBreak;
    _Bool _containsBlacklistedElements;
    _Bool _cancelled;
    NSLock *_lock;
    NSMutableAttributedString *_parsedAttributedString;
    unsigned long long _encoding;
    unsigned long long _maxLength;
    double _maxImageWidth;
    _Bool *_partiallyParsed;
    struct _xmlParserCtxt *_parserContext;
    NSMutableArray *_stringAttributesStack;
    NSMutableArray *_isQuoteElementStack;
    unsigned long long _currentQuoteLevel;
    NSMutableArray *_listStack;
    unsigned long long _currentListLevel;
    NSString *_ignoringElementSubtree;
    struct _xmlSAXHandler _parsingSAXHandler;
}

+ (struct CGSize)_scaledDownSize:(struct CGSize)arg1 maxWidth:(double)arg2;
+ (id)_scaleAndPrepareImageForClient:(id)arg1 maxWidth:(double)arg2 screenScale:(double)arg3;
+ (id)trimAttributedString:(id)arg1;
+ (id)adjustedImage:(id)arg1 maxWidth:(double)arg2 screenScale:(double)arg3;
+ (id)imageAttachmentAttributedStringWithContentId:(id)arg1 imageSize:(struct CGSize)arg2 mergingAttributes:(id)arg3;
+ (id)attachmentAttributedStringWithContentId:(id)arg1 mergingAttributes:(id)arg2;
@property(retain, nonatomic) NSString *ignoringElementSubtree; // @synthesize ignoringElementSubtree=_ignoringElementSubtree;
@property(nonatomic) _Bool cancelled; // @synthesize cancelled=_cancelled;
@property(nonatomic) _Bool containsBlacklistedElements; // @synthesize containsBlacklistedElements=_containsBlacklistedElements;
@property(nonatomic) _Bool isLastCharAddedLineBreak; // @synthesize isLastCharAddedLineBreak=_isLastCharAddedLineBreak;
@property(nonatomic) unsigned long long currentListLevel; // @synthesize currentListLevel=_currentListLevel;
@property(retain, nonatomic) NSMutableArray *listStack; // @synthesize listStack=_listStack;
@property(nonatomic) unsigned long long currentQuoteLevel; // @synthesize currentQuoteLevel=_currentQuoteLevel;
@property(retain, nonatomic) NSMutableArray *isQuoteElementStack; // @synthesize isQuoteElementStack=_isQuoteElementStack;
@property(retain, nonatomic) NSMutableArray *stringAttributesStack; // @synthesize stringAttributesStack=_stringAttributesStack;
@property(nonatomic) struct _xmlParserCtxt *parserContext; // @synthesize parserContext=_parserContext;
@property(nonatomic) struct _xmlSAXHandler parsingSAXHandler; // @synthesize parsingSAXHandler=_parsingSAXHandler;
@property(nonatomic) _Bool *partiallyParsed; // @synthesize partiallyParsed=_partiallyParsed;
@property(nonatomic) double maxImageWidth; // @synthesize maxImageWidth=_maxImageWidth;
@property(nonatomic) unsigned long long maxLength; // @synthesize maxLength=_maxLength;
@property(nonatomic) unsigned long long encoding; // @synthesize encoding=_encoding;
@property(retain, nonatomic) NSMutableAttributedString *parsedAttributedString; // @synthesize parsedAttributedString=_parsedAttributedString;
@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
- (void).cxx_destruct;
- (_Bool)_validateURLsAndHTMLTagsInParsedString:(id)arg1 urlsFound:(id *)arg2;
- (void)_addDataDetectionAttributes:(id)arg1;
- (void)_appendImageWithContentId:(id)arg1 imageSize:(struct CGSize)arg2;
- (void)_appendString:(id)arg1;
- (void)_requireNewLine;
- (void)_appendLineBreak;
- (void)_popStringAttributes;
- (void)_pushStringAttributes:(id)arg1;
- (id)_topStringAttributes;
- (void)_enumerateAttributes:(const char **)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)_valueForAttributeNamed:(id)arg1 inAttributes:(const char **)arg2;
- (unsigned long long)_writingDirectionFromString:(id)arg1;
- (unsigned long long)_textAlignmentFromString:(id)arg1;
- (id)_stringAttributeValueForCSSStyleName:(id)arg1 inStyleAttribute:(id)arg2;
- (id)_stringAttributesForStyleAttribute:(id)arg1;
- (void)_stringAttributeForElement:(id)arg1 attributes:(const char **)arg2 stringAttributeKey:(id *)arg3 stringAttributeValue:(id *)arg4;
- (_Bool)_isElementIgnorable:(id)arg1;
- (_Bool)_isElementBody:(id)arg1;
- (_Bool)_isElementImage:(id)arg1;
- (_Bool)_isElementListItem:(id)arg1;
- (_Bool)_isElementList:(id)arg1 ordered:(_Bool *)arg2;
- (_Bool)_isElementLineBreak:(id)arg1;
- (_Bool)_isElementQuoteElement:(id)arg1 attributes:(const char **)arg2;
- (_Bool)_isElementDisplayedInBlock:(id)arg1;
- (_Bool)_isErrorBlacklisted:(struct _xmlError *)arg1;
- (_Bool)_isElementBlacklisted:(id)arg1 attributes:(const char **)arg2;
- (id)_parseHTMLBody:(id)arg1 encoding:(unsigned long long)arg2 maxLength:(unsigned long long)arg3 maxImageWidth:(double)arg4 partiallyParsed:(_Bool *)arg5 urlsForValidation:(id)arg6 urlsFound:(id *)arg7;
- (id)parseHTMLBody:(id)arg1 encoding:(unsigned long long)arg2 maxLength:(unsigned long long)arg3 maxImageWidth:(double)arg4 partiallyParsed:(_Bool *)arg5 urlsForValidation:(id)arg6;
- (id)parseHTMLBody:(id)arg1 encoding:(unsigned long long)arg2 maxLength:(unsigned long long)arg3 maxImageWidth:(double)arg4 partiallyParsed:(_Bool *)arg5 urlsFound:(id *)arg6;
- (id)init;

@end

@interface NNMKProtoMessageContentSync : PBCodable <NSCopying>
{
    NSMutableArray *_attachments;
    NSData *_dateSynced;
    unsigned int _fullSyncVersion;
    NSString *_messageId;
    NSData *_preview;
    NSData *_text;
    _Bool _mainAlternativeValid;
    _Bool _partiallyLoaded;
    struct {
        unsigned int fullSyncVersion:1;
        unsigned int mainAlternativeValid:1;
        unsigned int partiallyLoaded:1;
    } _has;
}

@property(retain, nonatomic) NSMutableArray *attachments; // @synthesize attachments=_attachments;
@property(nonatomic) _Bool partiallyLoaded; // @synthesize partiallyLoaded=_partiallyLoaded;
@property(retain, nonatomic) NSData *preview; // @synthesize preview=_preview;
@property(retain, nonatomic) NSData *text; // @synthesize text=_text;
@property(nonatomic) _Bool mainAlternativeValid; // @synthesize mainAlternativeValid=_mainAlternativeValid;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(retain, nonatomic) NSData *dateSynced; // @synthesize dateSynced=_dateSynced;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)attachmentAtIndex:(unsigned long long)arg1;
- (unsigned long long)attachmentsCount;
- (void)addAttachment:(id)arg1;
- (void)clearAttachments;
@property(nonatomic) _Bool hasPartiallyLoaded;
@property(readonly, nonatomic) _Bool hasPreview;
@property(readonly, nonatomic) _Bool hasText;
@property(nonatomic) _Bool hasMainAlternativeValid;
@property(readonly, nonatomic) _Bool hasMessageId;
@property(readonly, nonatomic) _Bool hasDateSynced;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKMessageContentSyncServiceServer : NNMKSyncServiceEndpoint
{
    id <NNMKMessageContentSyncServiceServerDelegate> _delegate;
}

@property(nonatomic) __weak id <NNMKMessageContentSyncServiceServerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)readProtobufData:(id)arg1 type:(unsigned long long)arg2;
- (void)failedSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)successfullySentProtobufWithIDSIdentifier:(id)arg1;
- (id)notifyInitialContentSyncCompleted:(id)arg1;
- (id)syncImageAttachment:(id)arg1 notificationPriority:(_Bool)arg2 userRequested:(_Bool)arg3;
- (id)syncMessageContent:(id)arg1 notificationPriority:(_Bool)arg2 userRequested:(_Bool)arg3;
- (id)initWithQueue:(id)arg1;

@end

@interface NNMKProtoMessagesFilteredOutWarning : PBCodable <NSCopying>
{
    unsigned int _fullSyncVersion;
    NSMutableArray *_removedMessageIds;
    CDStruct_a125a100 _has;
}

@property(retain, nonatomic) NSMutableArray *removedMessageIds; // @synthesize removedMessageIds=_removedMessageIds;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)removedMessageIdAtIndex:(unsigned long long)arg1;
- (unsigned long long)removedMessageIdsCount;
- (void)addRemovedMessageId:(id)arg1;
- (void)clearRemovedMessageIds;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKProtoInitialMessagesSync : PBCodable <NSCopying>
{
    NSData *_dateForRequestingMoreMessages;
    NSData *_dateSynced;
    unsigned int _fullSyncVersion;
    NSMutableArray *_initialMessages;
    NSString *_syncedMailboxAccountId;
    NSString *_syncedMailboxCustomName;
    unsigned int _syncedMailboxType;
    NSString *_syncedMailboxURL;
    struct {
        unsigned int fullSyncVersion:1;
        unsigned int syncedMailboxType:1;
    } _has;
}

@property(retain, nonatomic) NSString *syncedMailboxCustomName; // @synthesize syncedMailboxCustomName=_syncedMailboxCustomName;
@property(retain, nonatomic) NSString *syncedMailboxURL; // @synthesize syncedMailboxURL=_syncedMailboxURL;
@property(retain, nonatomic) NSString *syncedMailboxAccountId; // @synthesize syncedMailboxAccountId=_syncedMailboxAccountId;
@property(nonatomic) unsigned int syncedMailboxType; // @synthesize syncedMailboxType=_syncedMailboxType;
@property(retain, nonatomic) NSData *dateForRequestingMoreMessages; // @synthesize dateForRequestingMoreMessages=_dateForRequestingMoreMessages;
@property(retain, nonatomic) NSMutableArray *initialMessages; // @synthesize initialMessages=_initialMessages;
@property(retain, nonatomic) NSData *dateSynced; // @synthesize dateSynced=_dateSynced;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasSyncedMailboxCustomName;
@property(readonly, nonatomic) _Bool hasSyncedMailboxURL;
@property(readonly, nonatomic) _Bool hasSyncedMailboxAccountId;
@property(nonatomic) _Bool hasSyncedMailboxType;
@property(readonly, nonatomic) _Bool hasDateForRequestingMoreMessages;
- (id)initialMessageAtIndex:(unsigned long long)arg1;
- (unsigned long long)initialMessagesCount;
- (void)addInitialMessage:(id)arg1;
- (void)clearInitialMessages;
@property(readonly, nonatomic) _Bool hasDateSynced;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKProtoInitialSyncFinishedNotification : PBCodable <NSCopying>
{
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKDeviceSyncRegistry : NSObject
{
    _Bool _isMessagesSyncActive;
    _Bool _organizeByThread;
    _Bool _isMoreMessagesRequestPending;
    NSString *_path;
    unsigned long long _fullMessagesSyncVersion;
    NSDate *_dateReceivedCapForAdding;
    NNMKSyncedMailbox *_syncedMailbox;
    double _deviceScreenWidth;
    double _deviceScreenScale;
    NNMKSQLiteConnection *_database;
}

@property(retain, nonatomic) NNMKSQLiteConnection *database; // @synthesize database=_database;
@property(nonatomic) _Bool isMoreMessagesRequestPending; // @synthesize isMoreMessagesRequestPending=_isMoreMessagesRequestPending;
@property(nonatomic) double deviceScreenScale; // @synthesize deviceScreenScale=_deviceScreenScale;
@property(nonatomic) double deviceScreenWidth; // @synthesize deviceScreenWidth=_deviceScreenWidth;
@property(nonatomic) _Bool organizeByThread; // @synthesize organizeByThread=_organizeByThread;
@property(retain, nonatomic) NNMKSyncedMailbox *syncedMailbox; // @synthesize syncedMailbox=_syncedMailbox;
@property(retain, nonatomic) NSDate *dateReceivedCapForAdding; // @synthesize dateReceivedCapForAdding=_dateReceivedCapForAdding;
@property(nonatomic) _Bool isMessagesSyncActive; // @synthesize isMessagesSyncActive=_isMessagesSyncActive;
@property(nonatomic) unsigned long long fullMessagesSyncVersion; // @synthesize fullMessagesSyncVersion=_fullMessagesSyncVersion;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (void)_insureTransactionFor:(CDUnknownBlockType)arg1;
- (id)_ungroupGroupedValue:(id)arg1;
- (id)_selectSyncedAccountsWhere:(id)arg1 blockForBinding:(CDUnknownBlockType)arg2;
- (id)_selectSyncedMessagesIdsWhere:(id)arg1 count:(unsigned long long)arg2 blockForBinding:(CDUnknownBlockType)arg3;
- (id)_selectSyncedMessagesWhere:(id)arg1 blockForBinding:(CDUnknownBlockType)arg2;
- (void)_deleteAllObjectsFromTable:(id)arg1;
- (void)_removeControlValueForKey:(id)arg1;
- (void)_setControlValueForKey:(id)arg1 withBlockForBinding:(CDUnknownBlockType)arg2;
- (void)_loadAllControlValues;
- (id)datesForIDSIdentifiersScheduledToBeResent;
- (void)rescheduleIDSIdentifier:(id)arg1 resendInterval:(unsigned long long)arg2 withDateToResend:(id)arg3;
- (void)markIDSIdentifierAsAckd:(id)arg1;
- (id)objectIdForIDSIdentifierNotYetAckd:(id)arg1 objectType:(id *)arg2 resendInterval:(unsigned long long *)arg3;
- (void)addObjectId:(id)arg1 objectType:(id)arg2 resendInterval:(unsigned long long)arg3 forIDSIdentifierNotYetAckd:(id)arg4;
- (id)syncedAccountIdsResendRequested;
- (void)removeSyncedAccountForAccountWithId:(id)arg1;
- (void)addOrUpdateSyncedAccount:(id)arg1;
- (id)syncedAccountForAccountWithId:(id)arg1;
- (id)allSyncedAccountsKeyedByAccountId;
- (id)syncedMessagesStatusKeyedByMessageIdAfterDateReceived:(id)arg1;
- (void)removeSyncedMessagesBeforeDateReceived:(id)arg1 adjustDateReceivedCapForAdding:(_Bool)arg2;
- (unsigned long long)syncedMessagesCount;
- (id)oldestDateReceived;
- (id)firstSyncedMessageIdsContentNotSyncedOrRequestedByUser:(unsigned long long)arg1;
- (id)syncedMessageIdsContentRequestedByUser;
- (id)syncedMessageIdsResendRequested;
- (id)syncedMessagesForConversationWithId:(id)arg1;
- (void)removeSyncedMessageForMessageWithId:(id)arg1;
- (void)addOrUpdateSyncedMessage:(id)arg1;
- (id)syncedMessageForMessageWithId:(id)arg1;
- (_Bool)containsSyncedMessageForMessageWithId:(id)arg1;
- (void)cleanUpForNewFullAccountsSync;
- (void)cleanUpForNewFullMessagesSync;
- (void)endUpdates;
- (void)beginUpdates;
- (void)setMoreMessagesRequestPending:(_Bool)arg1;
- (id)initWithPath:(id)arg1;

@end

@interface NNMKSyncedMessage : NSObject
{
    _Bool _usedNotificationPriorityForMessageSync;
    _Bool _contentSyncedUsingNotificationPriority;
    _Bool _contentSyncedBecauseUserRequested;
    _Bool _contentSynced;
    _Bool _contentRequestedByUser;
    _Bool _resendRequested;
    NSString *_messageId;
    unsigned long long _status;
    unsigned long long _statusVersion;
    NSDate *_dateReceived;
    NSMutableSet *_attachmentsContentIdsNotYetSynced;
    NSString *_conversationId;
    unsigned long long _resendInterval;
    unsigned long long _contentResendInterval;
}

@property(nonatomic) unsigned long long contentResendInterval; // @synthesize contentResendInterval=_contentResendInterval;
@property(nonatomic) unsigned long long resendInterval; // @synthesize resendInterval=_resendInterval;
@property(nonatomic) _Bool resendRequested; // @synthesize resendRequested=_resendRequested;
@property(retain, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(retain, nonatomic) NSMutableSet *attachmentsContentIdsNotYetSynced; // @synthesize attachmentsContentIdsNotYetSynced=_attachmentsContentIdsNotYetSynced;
@property(nonatomic) _Bool contentRequestedByUser; // @synthesize contentRequestedByUser=_contentRequestedByUser;
@property(nonatomic) _Bool contentSynced; // @synthesize contentSynced=_contentSynced;
@property(nonatomic) _Bool contentSyncedBecauseUserRequested; // @synthesize contentSyncedBecauseUserRequested=_contentSyncedBecauseUserRequested;
@property(nonatomic) _Bool contentSyncedUsingNotificationPriority; // @synthesize contentSyncedUsingNotificationPriority=_contentSyncedUsingNotificationPriority;
@property(nonatomic) _Bool usedNotificationPriorityForMessageSync; // @synthesize usedNotificationPriorityForMessageSync=_usedNotificationPriorityForMessageSync;
@property(retain, nonatomic) NSDate *dateReceived; // @synthesize dateReceived=_dateReceived;
@property(nonatomic) unsigned long long statusVersion; // @synthesize statusVersion=_statusVersion;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
- (void).cxx_destruct;
- (id)init;
- (id)initWithMessage:(id)arg1;

@end

@interface NNMKSyncedAccount : NSObject
{
    _Bool _shouldArchive;
    _Bool _resendRequested;
    NSString *_accountId;
    NSString *_displayName;
    unsigned long long _resendInterval;
}

@property(nonatomic) unsigned long long resendInterval; // @synthesize resendInterval=_resendInterval;
@property(nonatomic) _Bool resendRequested; // @synthesize resendRequested=_resendRequested;
@property(nonatomic) _Bool shouldArchive; // @synthesize shouldArchive=_shouldArchive;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
- (void).cxx_destruct;
- (id)init;
- (id)initWithAccount:(id)arg1;

@end

@interface NNMKSyncedMailbox : NSObject
{
    unsigned long long _type;
    NSString *_accountId;
    NSURL *_url;
    NSString *_customName;
}

@property(retain, nonatomic) NSString *customName; // @synthesize customName=_customName;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)init;

@end

@interface NNMKProtoMoreMessagesRequest : PBRequest <NSCopying>
{
    NSData *_beforeDateReceived;
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(retain, nonatomic) NSData *beforeDateReceived; // @synthesize beforeDateReceived=_beforeDateReceived;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasBeforeDateReceived;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKMessagesSyncServiceClient : NNMKSyncServiceEndpoint
{
    id <NNMKMessagesSyncServiceClientDelegate> _delegate;
}

@property(nonatomic) __weak id <NNMKMessagesSyncServiceClientDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)readProtobufData:(id)arg1 type:(unsigned long long)arg2;
- (void)connectivityChanged;
- (void)failedSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)successfullySentProtobufWithIDSIdentifier:(id)arg1;
- (id)sendMessage:(id)arg1;
- (void)requestCompactMessages:(id)arg1;
- (void)warnMessagesFilteredOut:(id)arg1;
- (id)deleteMessages:(id)arg1;
- (id)updateMessagesStatus:(id)arg1;
- (id)initWithQueue:(id)arg1;

@end

@interface NNMKProtoErrorDownloadingContentForMessageWarning : PBCodable <NSCopying>
{
    NSString *_messageId;
}

@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasMessageId;

@end

@interface NNMKAccount : NSObject <NSSecureCoding>
{
    _Bool _shouldArchive;
    NSString *_accountId;
    NSString *_displayName;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) _Bool shouldArchive; // @synthesize shouldArchive=_shouldArchive;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

@interface NNMKProtoContentRequest : PBRequest <NSCopying>
{
    unsigned int _fullSyncVersion;
    NSString *_messageId;
    _Bool _highPriority;
    struct {
        unsigned int fullSyncVersion:1;
        unsigned int highPriority:1;
    } _has;
}

@property(nonatomic) _Bool highPriority; // @synthesize highPriority=_highPriority;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasHighPriority;
@property(readonly, nonatomic) _Bool hasMessageId;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKProtoImageAttachmentSync : PBCodable <NSCopying>
{
    NSString *_contentId;
    NSData *_dateSynced;
    unsigned int _fullSyncVersion;
    NSData *_imageData;
    NSString *_messageId;
    CDStruct_a125a100 _has;
}

@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(retain, nonatomic) NSString *contentId; // @synthesize contentId=_contentId;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(retain, nonatomic) NSData *dateSynced; // @synthesize dateSynced=_dateSynced;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasImageData;
@property(readonly, nonatomic) _Bool hasContentId;
@property(readonly, nonatomic) _Bool hasMessageId;
@property(readonly, nonatomic) _Bool hasDateSynced;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKProtoMoreMessages : PBCodable <NSCopying>
{
    NSMutableArray *_addedMessages;
    NSData *_dateForRequestingMoreMessages;
    NSData *_dateSynced;
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(retain, nonatomic) NSData *dateForRequestingMoreMessages; // @synthesize dateForRequestingMoreMessages=_dateForRequestingMoreMessages;
@property(retain, nonatomic) NSMutableArray *addedMessages; // @synthesize addedMessages=_addedMessages;
@property(retain, nonatomic) NSData *dateSynced; // @synthesize dateSynced=_dateSynced;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasDateForRequestingMoreMessages;
- (id)addedMessageAtIndex:(unsigned long long)arg1;
- (unsigned long long)addedMessagesCount;
- (void)addAddedMessage:(id)arg1;
- (void)clearAddedMessages;
@property(readonly, nonatomic) _Bool hasDateSynced;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKSQLiteUtils : NSObject
{
}

+ (_Bool)boolFromStatement:(struct sqlite3_stmt *)arg1 columnIndex:(int)arg2;
+ (double)doubleFromStatement:(struct sqlite3_stmt *)arg1 columnIndex:(int)arg2;
+ (unsigned long long)unsignedIntegerFromStatement:(struct sqlite3_stmt *)arg1 columnIndex:(int)arg2;
+ (id)dataFromStatement:(struct sqlite3_stmt *)arg1 columnIndex:(int)arg2;
+ (id)dateFromStatement:(struct sqlite3_stmt *)arg1 columnIndex:(int)arg2;
+ (id)stringFromStatement:(struct sqlite3_stmt *)arg1 columnIndex:(int)arg2;
+ (void)bindBool:(_Bool)arg1 intoStatement:(struct sqlite3_stmt *)arg2 paramIndex:(int)arg3;
+ (void)bindDouble:(double)arg1 intoStatement:(struct sqlite3_stmt *)arg2 paramIndex:(int)arg3;
+ (void)bindUnsignedInteger:(unsigned long long)arg1 intoStatement:(struct sqlite3_stmt *)arg2 paramIndex:(int)arg3;
+ (void)bindData:(id)arg1 intoStatement:(struct sqlite3_stmt *)arg2 paramIndex:(int)arg3;
+ (void)bindDate:(id)arg1 intoStatement:(struct sqlite3_stmt *)arg2 paramIndex:(int)arg3;
+ (void)bindString:(id)arg1 intoStatement:(struct sqlite3_stmt *)arg2 paramIndex:(int)arg3;
+ (_Bool)isResponseOkFromPreparedStatementExecution:(int)arg1;
+ (void)closeExecutedPreparedStatement:(struct sqlite3_stmt *)arg1;

@end

@interface NNMKProtoPrepareForFullSyncRequest : PBRequest <NSCopying>
{
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKSyncServiceEndpoint : NSObject <IDSServiceDelegate>
{
    _Bool _isConnected;
    NSObject<OS_dispatch_queue> *_serviceQueue;
    IDSService *_idsService;
    NSString *_idsServiceName;
    NSMutableDictionary *_repeatPreventionRecords;
    NSObject<OS_dispatch_source> *_repeatPreventionCleanupTimer;
}

@property(retain, nonatomic) NSObject<OS_dispatch_source> *repeatPreventionCleanupTimer; // @synthesize repeatPreventionCleanupTimer=_repeatPreventionCleanupTimer;
@property(retain, nonatomic) NSMutableDictionary *repeatPreventionRecords; // @synthesize repeatPreventionRecords=_repeatPreventionRecords;
@property(retain, nonatomic) NSString *idsServiceName; // @synthesize idsServiceName=_idsServiceName;
@property(retain, nonatomic) IDSService *idsService; // @synthesize idsService=_idsService;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serviceQueue; // @synthesize serviceQueue=_serviceQueue;
@property(nonatomic) _Bool isConnected; // @synthesize isConnected=_isConnected;
- (void).cxx_destruct;
- (_Bool)_isConnected;
- (void)_handleConnectivityChange;
- (void)_removeExpiredRepeatPreventionRecords;
- (void)_storeRepeatPreventionId:(id)arg1 priority:(unsigned long long)arg2;
- (_Bool)_willIdRepeat:(id)arg1;
- (void)service:(id)arg1 nearbyDevicesChanged:(id)arg2;
- (void)service:(id)arg1 devicesChanged:(id)arg2;
- (void)service:(id)arg1 activeAccountsChanged:(id)arg2;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 hasBeenDeliveredWithContext:(id)arg4;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5;
- (void)service:(id)arg1 account:(id)arg2 incomingUnhandledProtobuf:(id)arg3 fromID:(id)arg4 context:(id)arg5;
- (id)_sendProtobufData:(id)arg1 type:(unsigned long long)arg2 priority:(unsigned long long)arg3 shortTimeout:(_Bool)arg4;
- (id)sendProtobufData:(id)arg1 type:(unsigned long long)arg2 priority:(unsigned long long)arg3 repeatPreventionId:(id)arg4 shortTimeout:(_Bool)arg5;
- (id)sendProtobufData:(id)arg1 type:(unsigned long long)arg2 priority:(unsigned long long)arg3 shortTimeout:(_Bool)arg4;
- (void)connectivityChanged;
- (void)readProtobufData:(id)arg1 type:(unsigned long long)arg2;
- (void)failedSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)successfullySentProtobufWithIDSIdentifier:(id)arg1;
- (void)resetRepeatPreventionHistory;
- (void)dealloc;
- (id)initWithIDSServiceName:(id)arg1 queue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NNMKMessagesSyncServiceServer : NNMKSyncServiceEndpoint
{
    id <NNMKMessagesSyncServiceServerDelegate> _delegate;
}

@property(nonatomic) __weak id <NNMKMessagesSyncServiceServerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)readProtobufData:(id)arg1 type:(unsigned long long)arg2;
- (void)failedSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)successfullySentProtobufWithIDSIdentifier:(id)arg1;
- (id)sendMoreMessagesForConversation:(id)arg1;
- (id)sendMoreMessages:(id)arg1;
- (id)sendInitialMessagesSync:(id)arg1;
- (id)addMessages:(id)arg1 notificationPriority:(_Bool)arg2;
- (id)deleteMessages:(id)arg1 notificationPriority:(_Bool)arg2;
- (id)updateMessagesStatus:(id)arg1 notificationPriority:(_Bool)arg2;
- (id)initWithQueue:(id)arg1;

@end

@interface NNMKProtoMoreMessagesForConversation : PBCodable <NSCopying>
{
    NSMutableArray *_addedMessages;
    NSString *_conversationId;
    NSData *_dateSynced;
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(retain, nonatomic) NSMutableArray *addedMessages; // @synthesize addedMessages=_addedMessages;
@property(retain, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(retain, nonatomic) NSData *dateSynced; // @synthesize dateSynced=_dateSynced;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)addedMessageAtIndex:(unsigned long long)arg1;
- (unsigned long long)addedMessagesCount;
- (void)addAddedMessage:(id)arg1;
- (void)clearAddedMessages;
@property(readonly, nonatomic) _Bool hasConversationId;
@property(readonly, nonatomic) _Bool hasDateSynced;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKFetchesSyncServiceServer : NNMKSyncServiceEndpoint
{
    id <NNMKFetchesSyncServiceServerDelegate> _delegate;
}

@property(nonatomic) __weak id <NNMKFetchesSyncServiceServerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)readProtobufData:(id)arg1 type:(unsigned long long)arg2;
- (void)failedSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)successfullySentProtobufWithIDSIdentifier:(id)arg1;
- (void)notifyFetchRequestCompleted:(id)arg1;
- (void)notifyOldMessagesAvailable:(id)arg1;
- (void)warnErrorDownloadingContentForMessage:(id)arg1 notificationPriority:(_Bool)arg2 userRequested:(_Bool)arg3;
- (void)warnNeedsUnlock:(id)arg1;
- (void)requestPrepareForFullSync:(id)arg1;
- (id)initWithQueue:(id)arg1;

@end

@interface NNMKProtoFullSyncRequest : PBRequest <NSCopying>
{
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKSQLiteConnection : NSObject
{
    _Bool _isInTransaction;
    struct sqlite3 *_db;
    NSObject<OS_dispatch_queue> *_dbQueue;
    NSMutableDictionary *_cachedPreparedStatementsKeyedBySQLPattern;
}

+ (_Bool)errorCodeMeansCorruptedDatabase:(int)arg1;
@property(retain, nonatomic) NSMutableDictionary *cachedPreparedStatementsKeyedBySQLPattern; // @synthesize cachedPreparedStatementsKeyedBySQLPattern=_cachedPreparedStatementsKeyedBySQLPattern;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dbQueue; // @synthesize dbQueue=_dbQueue;
@property(nonatomic) _Bool isInTransaction; // @synthesize isInTransaction=_isInTransaction;
@property(nonatomic) struct sqlite3 *db; // @synthesize db=_db;
- (void).cxx_destruct;
- (int)_runRetryingIfNeeded:(CDUnknownBlockType)arg1;
- (id)_lastErrorMessage;
- (int)_lastErrorCode;
- (int)_executeSQL:(id)arg1;
- (int)_stepPreparedStatement:(struct sqlite3_stmt *)arg1;
- (struct sqlite3_stmt *)_preparedStatementForPattern:(id)arg1 cacheStatement:(_Bool)arg2;
- (void)_closeDatabase;
- (_Bool)_openDatabaseWithPath:(id)arg1 protectData:(_Bool)arg2 errorCode:(int *)arg3;
- (_Bool)tableExists:(id)arg1 inDatabase:(id)arg2;
- (id)lastErrorMessage;
- (int)lastErrorCode;
- (_Bool)rollbackTransaction;
- (_Bool)commitTransaction;
- (_Bool)beginTransaction;
- (int)executeSQL:(id)arg1;
- (int)stepPreparedStatement:(struct sqlite3_stmt *)arg1;
- (struct sqlite3_stmt *)preparedStatementForPattern:(id)arg1 cacheStatement:(_Bool)arg2;
- (struct sqlite3_stmt *)preparedStatementForPattern:(id)arg1;
- (void)dealloc;
- (id)initWithPath:(id)arg1 protectData:(_Bool)arg2 errorCode:(int *)arg3;

@end

@interface NNMKProtoMessageDeletion : PBCodable <NSCopying>
{
    unsigned int _deletionState;
    NSString *_messageId;
    struct {
        unsigned int deletionState:1;
    } _has;
}

@property(nonatomic) unsigned int deletionState; // @synthesize deletionState=_deletionState;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasDeletionState;
@property(readonly, nonatomic) _Bool hasMessageId;

@end

@interface NNMKProtoMessageStatusUpdates : PBCodable <NSCopying>
{
    NSData *_dateSynced;
    unsigned int _fullSyncVersion;
    NSMutableArray *_messageStatusUpdates;
    CDStruct_a125a100 _has;
}

@property(retain, nonatomic) NSMutableArray *messageStatusUpdates; // @synthesize messageStatusUpdates=_messageStatusUpdates;
@property(retain, nonatomic) NSData *dateSynced; // @synthesize dateSynced=_dateSynced;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)messageStatusUpdateAtIndex:(unsigned long long)arg1;
- (unsigned long long)messageStatusUpdatesCount;
- (void)addMessageStatusUpdate:(id)arg1;
- (void)clearMessageStatusUpdates;
@property(readonly, nonatomic) _Bool hasDateSynced;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKMessageContent : NSObject <NSSecureCoding>
{
    _Bool _mainAlternativeValid;
    _Bool _partiallyLoaded;
    NSString *_messageId;
    NSData *_textData;
    NSArray *_attachments;
}

+ (id)classesForUnarchivingTextData;
+ (_Bool)supportsSecureCoding;
@property(nonatomic) _Bool partiallyLoaded; // @synthesize partiallyLoaded=_partiallyLoaded;
@property(retain, nonatomic) NSArray *attachments; // @synthesize attachments=_attachments;
@property(retain, nonatomic) NSData *textData; // @synthesize textData=_textData;
@property(nonatomic) _Bool mainAlternativeValid; // @synthesize mainAlternativeValid=_mainAlternativeValid;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

@interface NNMKAttachment : NSTextAttachment <NSSecureCoding>
{
    NSString *_contentId;
    NSString *_fileName;
    unsigned long long _fileSize;
    unsigned long long _type;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(retain, nonatomic) NSString *contentId; // @synthesize contentId=_contentId;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

@interface NNMKImageAttachment : NNMKAttachment <NSSecureCoding>
{
    _Bool _renderOnClient;
    struct CGSize _imageSize;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(nonatomic) _Bool renderOnClient; // @synthesize renderOnClient=_renderOnClient;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

@interface NNMKAccountsSyncServiceClient : NNMKSyncServiceEndpoint
{
    id <NNMKAccountsSyncServiceClientDelegate> _delegate;
}

@property(nonatomic) __weak id <NNMKAccountsSyncServiceClientDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)readProtobufData:(id)arg1 type:(unsigned long long)arg2;
- (void)failedSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)successfullySentProtobufWithIDSIdentifier:(id)arg1;
- (id)initWithQueue:(id)arg1;

@end

@interface NNMKProtoCompactMessagesRequest : PBRequest <NSCopying>
{
    NSData *_beforeDateReceived;
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(retain, nonatomic) NSData *beforeDateReceived; // @synthesize beforeDateReceived=_beforeDateReceived;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasBeforeDateReceived;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKProtoAccountAdditionOrUpdate : PBCodable <NSCopying>
{
    NSString *_accountId;
    NSString *_displayName;
    _Bool _shouldArchive;
    struct {
        unsigned int shouldArchive:1;
    } _has;
}

@property(nonatomic) _Bool shouldArchive; // @synthesize shouldArchive=_shouldArchive;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasShouldArchive;
@property(readonly, nonatomic) _Bool hasDisplayName;
@property(readonly, nonatomic) _Bool hasAccountId;

@end

@interface NNMKProtoMessage : PBCodable <NSCopying>
{
    NSString *_accountId;
    NSMutableArray *_ccs;
    NSString *_conversationId;
    NSData *_dateReceived;
    NSData *_dateSent;
    NSString *_from;
    NSString *_messageId;
    NSString *_messageIdHeader;
    unsigned int _status;
    NSString *_subject;
    NSMutableArray *_tos;
    struct {
        unsigned int status:1;
    } _has;
}

@property(retain, nonatomic) NSString *messageIdHeader; // @synthesize messageIdHeader=_messageIdHeader;
@property(retain, nonatomic) NSData *dateReceived; // @synthesize dateReceived=_dateReceived;
@property(retain, nonatomic) NSData *dateSent; // @synthesize dateSent=_dateSent;
@property(retain, nonatomic) NSMutableArray *ccs; // @synthesize ccs=_ccs;
@property(retain, nonatomic) NSMutableArray *tos; // @synthesize tos=_tos;
@property(retain, nonatomic) NSString *from; // @synthesize from=_from;
@property(nonatomic) unsigned int status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *subject; // @synthesize subject=_subject;
@property(retain, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasMessageIdHeader;
@property(readonly, nonatomic) _Bool hasDateReceived;
@property(readonly, nonatomic) _Bool hasDateSent;
- (id)ccAtIndex:(unsigned long long)arg1;
- (unsigned long long)ccsCount;
- (void)addCc:(id)arg1;
- (void)clearCcs;
- (id)toAtIndex:(unsigned long long)arg1;
- (unsigned long long)tosCount;
- (void)addTo:(id)arg1;
- (void)clearTos;
@property(readonly, nonatomic) _Bool hasFrom;
@property(nonatomic) _Bool hasStatus;
@property(readonly, nonatomic) _Bool hasSubject;
@property(readonly, nonatomic) _Bool hasConversationId;
@property(readonly, nonatomic) _Bool hasAccountId;
@property(readonly, nonatomic) _Bool hasMessageId;

@end

@interface NNMKProtoMessageDeletions : PBCodable <NSCopying>
{
    NSData *_dateSynced;
    unsigned int _fullSyncVersion;
    NSMutableArray *_messageDeletions;
    CDStruct_a125a100 _has;
}

@property(retain, nonatomic) NSMutableArray *messageDeletions; // @synthesize messageDeletions=_messageDeletions;
@property(retain, nonatomic) NSData *dateSynced; // @synthesize dateSynced=_dateSynced;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)messageDeletionAtIndex:(unsigned long long)arg1;
- (unsigned long long)messageDeletionsCount;
- (void)addMessageDeletion:(id)arg1;
- (void)clearMessageDeletions;
@property(readonly, nonatomic) _Bool hasDateSynced;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKMessageContentSyncServiceClient : NNMKSyncServiceEndpoint
{
    id <NNMKMessageContentSyncServiceClientDelegate> _delegate;
}

@property(nonatomic) __weak id <NNMKMessageContentSyncServiceClientDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)readProtobufData:(id)arg1 type:(unsigned long long)arg2;
- (void)failedSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)successfullySentProtobufWithIDSIdentifier:(id)arg1;
- (id)initWithQueue:(id)arg1;

@end

@interface NNMKProtoNeedsUnlockWarning : PBCodable <NSCopying>
{
}

- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;

@end

@interface NNMKProtoFetchRequestCompletedNotification : PBCodable <NSCopying>
{
}

- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;

@end

@interface NNMKProtoFetchRequest : PBRequest <NSCopying>
{
    NSString *_conversationId;
    unsigned int _fullSyncVersion;
    _Bool _manuallyTriggered;
    struct {
        unsigned int fullSyncVersion:1;
        unsigned int manuallyTriggered:1;
    } _has;
}

@property(retain, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(nonatomic) _Bool manuallyTriggered; // @synthesize manuallyTriggered=_manuallyTriggered;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasConversationId;
@property(nonatomic) _Bool hasManuallyTriggered;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKProtoInitialContentSyncCompletedNotification : PBCodable <NSCopying>
{
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKMessage : NSObject <NNMKMailboxItem, NSSecureCoding>
{
    NSString *_subject;
    NSDate *_dateReceived;
    NSString *_preview;
    unsigned long long _status;
    NSString *_messageId;
    NSString *_accountId;
    NSString *_conversationId;
    NSString *_from;
    NSArray *_to;
    NSArray *_cc;
    NSDate *_dateSent;
    NSString *_messageIdHeader;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSString *messageIdHeader; // @synthesize messageIdHeader=_messageIdHeader;
@property(retain, nonatomic) NSDate *dateSent; // @synthesize dateSent=_dateSent;
@property(retain, nonatomic) NSArray *cc; // @synthesize cc=_cc;
@property(retain, nonatomic) NSArray *to; // @synthesize to=_to;
@property(retain, nonatomic) NSString *from; // @synthesize from=_from;
@property(retain, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *preview; // @synthesize preview=_preview;
@property(retain, nonatomic) NSDate *dateReceived; // @synthesize dateReceived=_dateReceived;
@property(retain, nonatomic) NSString *subject; // @synthesize subject=_subject;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)removeState:(unsigned long long)arg1;
- (void)addState:(unsigned long long)arg1;
- (_Bool)checkState:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NNMKSQLJournal : NSObject
{
    NSString *_directoryPath;
    NSMutableData *_currentFileData;
    NSObject<OS_dispatch_queue> *_journalQueue;
    unsigned long long _filesCount;
}

@property(nonatomic) unsigned long long filesCount; // @synthesize filesCount=_filesCount;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *journalQueue; // @synthesize journalQueue=_journalQueue;
@property(retain, nonatomic) NSMutableData *currentFileData; // @synthesize currentFileData=_currentFileData;
@property(retain, nonatomic) NSString *directoryPath; // @synthesize directoryPath=_directoryPath;
- (void).cxx_destruct;
- (id)_sortedJournalFiles;
- (id)_nextFilePath;
- (void)_flush;
- (unsigned long long)_currentFilesCount;
- (void)mergeUsingBlock:(CDUnknownBlockType)arg1;
- (void)flushIfNeeded;
- (void)appendSQLStatement:(id)arg1;
- (id)initWithPath:(id)arg1;

@end

@interface NNMKProtoOldMessagesAvailableNotification : PBCodable <NSCopying>
{
    unsigned int _fullSyncVersion;
    CDStruct_a125a100 _has;
}

@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKProtoInitialAccountsSync : PBCodable <NSCopying>
{
    NSMutableArray *_initialAccounts;
}

@property(retain, nonatomic) NSMutableArray *initialAccounts; // @synthesize initialAccounts=_initialAccounts;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)initialAccountAtIndex:(unsigned long long)arg1;
- (unsigned long long)initialAccountsCount;
- (void)addInitialAccount:(id)arg1;
- (void)clearInitialAccounts;

@end

@interface NNMKProtoMessageAdditions : PBCodable <NSCopying>
{
    NSData *_dateForRequestingMoreMessages;
    NSData *_dateSynced;
    unsigned int _fullSyncVersion;
    NSMutableArray *_messageAdditions;
    _Bool _messagesAreNew;
    struct {
        unsigned int fullSyncVersion:1;
        unsigned int messagesAreNew:1;
    } _has;
}

@property(nonatomic) _Bool messagesAreNew; // @synthesize messagesAreNew=_messagesAreNew;
@property(retain, nonatomic) NSData *dateForRequestingMoreMessages; // @synthesize dateForRequestingMoreMessages=_dateForRequestingMoreMessages;
@property(retain, nonatomic) NSMutableArray *messageAdditions; // @synthesize messageAdditions=_messageAdditions;
@property(retain, nonatomic) NSData *dateSynced; // @synthesize dateSynced=_dateSynced;
@property(nonatomic) unsigned int fullSyncVersion; // @synthesize fullSyncVersion=_fullSyncVersion;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasMessagesAreNew;
@property(readonly, nonatomic) _Bool hasDateForRequestingMoreMessages;
- (id)messageAdditionAtIndex:(unsigned long long)arg1;
- (unsigned long long)messageAdditionsCount;
- (void)addMessageAddition:(id)arg1;
- (void)clearMessageAdditions;
@property(readonly, nonatomic) _Bool hasDateSynced;
@property(nonatomic) _Bool hasFullSyncVersion;

@end

@interface NNMKSyncProvider : NNMKSyncEndpoint <NNMKMessagesSyncServiceServerDelegate, NNMKMessageContentSyncServiceServerDelegate, NNMKAccountsSyncServiceServerDelegate, NNMKFetchesSyncServiceServerDelegate, PSYSyncCoordinatorDelegate>
{
    _Bool _messagesVerificationTriggered;
    _Bool _messagesQueryAvailable;
    _Bool _isFirstMessagesRequestPending;
    _Bool _trackingInitialSync;
    id <NNMKSyncProviderDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_providerQueue;
    BLTPingSubscriber *_notificationsPingSubscriber;
    PSYSyncCoordinator *_initialSyncCoordinator;
    NNMKDeviceSyncRegistry *_pairedDeviceRegistry;
    NNMKMessagesSyncServiceServer *_messagesSyncService;
    NNMKMessageContentSyncServiceServer *_contentSyncService;
    NNMKAccountsSyncServiceServer *_accountsSyncService;
    NNMKFetchesSyncServiceServer *_fetchesSyncService;
    NSString *_pendingMoreMessagesForConversationIdRequestConversationId;
    NSDate *_pendingMoreMessagesForConversationIdRequestBeforeDateReceived;
    NSMutableSet *_messageIdsToIgnoreStatusUpdates;
    unsigned long long _initialSyncResendInterval;
    double _initialSyncProgress;
    unsigned long long _initialSyncMessagesCount;
    NSMutableSet *_initialSyncMessageIdsToSyncContent;
    NSMutableSet *_initialSyncMessageIdsOfContentToAck;
}

@property(retain, nonatomic) NSMutableSet *initialSyncMessageIdsOfContentToAck; // @synthesize initialSyncMessageIdsOfContentToAck=_initialSyncMessageIdsOfContentToAck;
@property(retain, nonatomic) NSMutableSet *initialSyncMessageIdsToSyncContent; // @synthesize initialSyncMessageIdsToSyncContent=_initialSyncMessageIdsToSyncContent;
@property(nonatomic) unsigned long long initialSyncMessagesCount; // @synthesize initialSyncMessagesCount=_initialSyncMessagesCount;
@property(nonatomic) double initialSyncProgress; // @synthesize initialSyncProgress=_initialSyncProgress;
@property(nonatomic) _Bool trackingInitialSync; // @synthesize trackingInitialSync=_trackingInitialSync;
@property(nonatomic) unsigned long long initialSyncResendInterval; // @synthesize initialSyncResendInterval=_initialSyncResendInterval;
@property(retain, nonatomic) NSMutableSet *messageIdsToIgnoreStatusUpdates; // @synthesize messageIdsToIgnoreStatusUpdates=_messageIdsToIgnoreStatusUpdates;
@property(retain, nonatomic) NSDate *pendingMoreMessagesForConversationIdRequestBeforeDateReceived; // @synthesize pendingMoreMessagesForConversationIdRequestBeforeDateReceived=_pendingMoreMessagesForConversationIdRequestBeforeDateReceived;
@property(retain, nonatomic) NSString *pendingMoreMessagesForConversationIdRequestConversationId; // @synthesize pendingMoreMessagesForConversationIdRequestConversationId=_pendingMoreMessagesForConversationIdRequestConversationId;
@property(nonatomic) _Bool isFirstMessagesRequestPending; // @synthesize isFirstMessagesRequestPending=_isFirstMessagesRequestPending;
@property(nonatomic) _Bool messagesQueryAvailable; // @synthesize messagesQueryAvailable=_messagesQueryAvailable;
@property(retain, nonatomic) NNMKFetchesSyncServiceServer *fetchesSyncService; // @synthesize fetchesSyncService=_fetchesSyncService;
@property(retain, nonatomic) NNMKAccountsSyncServiceServer *accountsSyncService; // @synthesize accountsSyncService=_accountsSyncService;
@property(retain, nonatomic) NNMKMessageContentSyncServiceServer *contentSyncService; // @synthesize contentSyncService=_contentSyncService;
@property(retain, nonatomic) NNMKMessagesSyncServiceServer *messagesSyncService; // @synthesize messagesSyncService=_messagesSyncService;
@property(nonatomic) _Bool messagesVerificationTriggered; // @synthesize messagesVerificationTriggered=_messagesVerificationTriggered;
@property(retain, nonatomic) NNMKDeviceSyncRegistry *pairedDeviceRegistry; // @synthesize pairedDeviceRegistry=_pairedDeviceRegistry;
@property(retain, nonatomic) PSYSyncCoordinator *initialSyncCoordinator; // @synthesize initialSyncCoordinator=_initialSyncCoordinator;
@property(retain, nonatomic) BLTPingSubscriber *notificationsPingSubscriber; // @synthesize notificationsPingSubscriber=_notificationsPingSubscriber;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *providerQueue; // @synthesize providerQueue=_providerQueue;
@property(nonatomic) __weak id <NNMKSyncProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)_messageHasContentCompletelySynced:(id)arg1;
- (id)_syncedMailboxForGetters;
- (void)_incrementInitialSyncProgressBy:(double)arg1;
- (void)_requestDelegateForVerificationOfMessagesAndIds:(id)arg1 afterDate:(id)arg2;
- (void)_requestDelegateForResendingAccountWithId:(id)arg1;
- (void)_requestDelegateForResendingMessageWithId:(id)arg1;
- (void)_requestDelegateToSendMessageTo:(id)arg1 cc:(id)arg2 subject:(id)arg3 body:(id)arg4;
- (void)_requestDelegateForFetchManualForConversationId:(id)arg1;
- (void)_requestDelegateForFetchResume;
- (void)_requestDelegateToStopDownloadingAllContentAndAttachments;
- (void)_requestDelegateToStopDownloadingContentAndAttachmentsForMessageWithId:(id)arg1;
- (void)_requestDelegateForContentForMessageWithId:(id)arg1 highPriority:(_Bool)arg2;
- (void)_requestDelegateForContentForMessageIds:(id)arg1 highPriority:(_Bool)arg2;
- (void)_requestDelegateForFirstMessages;
- (void)_requestDelegateForMoreMessagesBeforeDateReceived:(id)arg1 forConversationWithId:(id)arg2;
- (void)_requestDelegateForMoreMessages;
- (void)_requestDelegateForAccounts;
- (void)_notifyDelegateThatMessagesStatusWereUpdated:(id)arg1;
- (void)_resendPendingAccountWithIds:(id)arg1 forIDSIdentifier:(id)arg2 newResendInterval:(unsigned long long)arg3;
- (void)_resendPendingMessageContentWithId:(id)arg1 sentBecauseUserRequested:(_Bool)arg2 idsIdentifier:(id)arg3 newResendInterval:(unsigned long long)arg4;
- (void)_resendPendingMessagesWithIds:(id)arg1 forIDSIdentifier:(id)arg2 newResendInterval:(unsigned long long)arg3;
- (void)_resendInitialSyncWithIDSIdentifier:(id)arg1 newResendInterval:(unsigned long long)arg2;
- (void)_resendObjectId:(id)arg1 objectType:(id)arg2 resendInterval:(unsigned long long)arg3 idsIdentifier:(id)arg4;
- (void)_scheduleIdsIdentifierForResend:(id)arg1 currentResendInterval:(unsigned long long)arg2 newResendInterval:(unsigned long long)arg3;
- (void)_handleDidSendProtobufSuccessfullyWithIDSIdentifier:(id)arg1;
- (void)_handleDidFailSendingProtobufWithIDSIdentifier:(id)arg1 errorCode:(long long)arg2;
- (void)_handleInitialSyncCompleted;
- (void)_handleMessageCompletelySynced:(id)arg1;
- (void)_executePendingContentRequests;
- (void)_sendFirstUnsyncedAndUnrequestedContents;
- (void)_executePendingResends;
- (void)_executePendingRequests;
- (void)_warnReceiverNeedsUnlock;
- (id)_messageProtobufForMessage:(id)arg1;
- (_Bool)_isDateReceivedOkForCurrentSyncedMailbox:(id)arg1;
- (_Bool)_isMessageStatusOkForCurrentSyncedMailbox:(unsigned long long)arg1;
- (_Bool)_currentSyncedMailboxAddsDeletesMessagesByStatusUpdates;
- (_Bool)_isMessageOkForCurrentSyncedMailbox:(id)arg1;
- (id)_filterOutMessagesReceivedByDateReceived:(id)arg1;
- (id)_filterOutMessagesReceived:(id)arg1 byAlreadySynced:(_Bool)arg2 bySyncedMailboxType:(_Bool)arg3;
- (void)_notifyClientNotifyInitialContentSyncCompleted;
- (void)_runSyncVerification;
- (void)_triggerFullMessagesSyncWithAccountsSync:(_Bool)arg1;
- (void)_triggerFullMessagesAndAccountsSync;
- (void)_triggerFullMessagesSync;
- (id)_bbSubsectionIdsForMessage:(id)arg1;
- (_Bool)_willPresentNotificationForMessage:(id)arg1;
- (void)_markConversationWithId:(id)arg1 forNotify:(_Bool)arg2;
- (void)_addMessages:(id)arg1 messagesAreNew:(_Bool)arg2;
- (_Bool)_verifyDatabaseOkForFullSyncVersion:(unsigned long long)arg1;
- (void)_storeScreenRelatedValuesForPairedDevice:(id)arg1;
- (void)_verifyPairingForcingSync:(_Bool)arg1;
- (void)_handleDidUnpair;
- (void)_handleDidPairWithNewDevice;
- (void)syncCoordinatorDidReceiveStartSyncCommand:(id)arg1;
- (void)fetchesSyncServiceServer:(id)arg1 didNotifyInitialSyncFinished:(id)arg2;
- (void)fetchesSyncServiceServer:(id)arg1 didRequestFullSync:(id)arg2;
- (void)fetchesSyncServiceServer:(id)arg1 didRequestContent:(id)arg2;
- (void)fetchesSyncServiceServer:(id)arg1 didRequestMoreMessagesForConversation:(id)arg2;
- (void)fetchesSyncServiceServer:(id)arg1 didRequestMoreMessages:(id)arg2;
- (void)fetchesSyncServiceServer:(id)arg1 didRequestFetch:(id)arg2;
- (void)accountsSyncServiceServer:(id)arg1 didSendProtobufSuccessfullyWithIDSIdentifier:(id)arg2;
- (void)accountsSyncServiceServer:(id)arg1 didFailSendingProtobufWithIDSIdentifier:(id)arg2 errorCode:(long long)arg3;
- (void)messageContentSyncServiceServer:(id)arg1 didSendProtobufSuccessfullyWithIDSIdentifier:(id)arg2;
- (void)messageContentSyncServiceServer:(id)arg1 didFailSendingProtobufWithIDSIdentifier:(id)arg2 errorCode:(long long)arg3;
- (void)messagesSyncServiceServer:(id)arg1 didRequestCompactMessages:(id)arg2;
- (void)messagesSyncServiceServer:(id)arg1 didWarnMessagesFilteredOut:(id)arg2;
- (void)messagesSyncServiceServer:(id)arg1 didRequestSendMessage:(id)arg2;
- (void)messagesSyncServiceServer:(id)arg1 didDeleteMessages:(id)arg2;
- (void)messagesSyncServiceServer:(id)arg1 didUpdateMessagesStatus:(id)arg2;
- (void)messagesSyncServiceServer:(id)arg1 didSendProtobufSuccessfullyWithIDSIdentifier:(id)arg2;
- (void)messagesSyncServiceServer:(id)arg1 didFailSendingProtobufWithIDSIdentifier:(id)arg2 errorCode:(long long)arg3;
- (void)resendIDSIdentifier:(id)arg1;
@property(readonly, nonatomic) NNMKPairedDeviceInfo *pairedDeviceInfo;
@property(readonly, nonatomic) _Bool organizeByThread;
@property(readonly, nonatomic) NSString *syncedMailboxCustomName;
@property(readonly, nonatomic) NSURL *syncedMailboxURL;
@property(readonly, nonatomic) NSString *syncedMailboxAccountId;
@property(readonly, nonatomic) unsigned long long syncedMailboxType;
@property(readonly, nonatomic) _Bool messagesSyncActive;
- (id)bulletinFlagsForMessageStatus:(unsigned long long)arg1 dateReceived:(id)arg2 messageWillBeAddedToSyncProvider:(_Bool)arg3;
- (void)notifyFetchManualCompleted;
- (void)notifyOrganizeByThreadChanged;
- (void)notifySyncedMailboxChanged;
- (void)notifyMessagesQueryAvailable;
- (void)notifyMessagesQueryUnavailable;
- (void)addUpdateOrDeleteAccounts:(id)arg1;
- (void)addImageAttachment:(id)arg1 forMessageId:(id)arg2 contentId:(id)arg3;
- (void)reportMessageContentDownloadFailureForMessageId:(id)arg1;
- (void)addMessageContent:(id)arg1 preview:(id)arg2;
- (void)markConversationIdForNotNotify:(id)arg1;
- (void)markConversationIdForNotify:(id)arg1 messages:(id)arg2;
- (void)deleteMessagesWithIds:(id)arg1;
- (void)updateMessagesStatus:(id)arg1;
- (void)addMessages:(id)arg1;
- (void)replyWithVerificationResultsMessagesMissing:(id)arg1 messagesWithDifferentStatus:(id)arg2 extraMessageIds:(id)arg3;
- (void)replyWithAccountToResend:(id)arg1;
- (void)replyWithMessageToResend:(id)arg1;
- (void)replyWithAccounts:(id)arg1;
- (void)replyWithMessagesFailedDueToDataProtectedForDateReceivedBefore:(id)arg1 conversationId:(id)arg2;
- (void)replyWithMoreMessages:(id)arg1 forConversationWithId:(id)arg2;
- (void)replyWithMoreMessages:(id)arg1 forDateReceivedBefore:(id)arg2;
- (void)replyWithFirstMessages:(id)arg1 syncedMailboxType:(unsigned long long)arg2 syncedMailboxAccountId:(id)arg3 syncedMailboxURL:(id)arg4 syncedMailboxCustomName:(id)arg5 organizeByThread:(_Bool)arg6;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NNMKProtoAttachmentMetadata : PBCodable <NSCopying>
{
    NSString *_contentId;
    NSString *_fileName;
    unsigned int _fileSize;
    float _imageHeight;
    float _imageWidth;
    unsigned int _type;
    _Bool _renderOnClient;
    struct {
        unsigned int fileSize:1;
        unsigned int imageHeight:1;
        unsigned int imageWidth:1;
        unsigned int type:1;
        unsigned int renderOnClient:1;
    } _has;
}

@property(nonatomic) float imageHeight; // @synthesize imageHeight=_imageHeight;
@property(nonatomic) float imageWidth; // @synthesize imageWidth=_imageWidth;
@property(nonatomic) _Bool renderOnClient; // @synthesize renderOnClient=_renderOnClient;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(nonatomic) unsigned int fileSize; // @synthesize fileSize=_fileSize;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(retain, nonatomic) NSString *contentId; // @synthesize contentId=_contentId;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasImageHeight;
@property(nonatomic) _Bool hasImageWidth;
@property(nonatomic) _Bool hasRenderOnClient;
@property(nonatomic) _Bool hasType;
@property(nonatomic) _Bool hasFileSize;
@property(readonly, nonatomic) _Bool hasFileName;
@property(readonly, nonatomic) _Bool hasContentId;

@end

@interface UIColor (NNMKWebColors)
+ (id)colorWithWebHexTriplet:(id)arg1;
+ (id)colorWithWebRgb:(id)arg1;
+ (id)colorWithWebColorName:(id)arg1;
+ (id)colorWithWebColor:(id)arg1;
@end

@interface NSData (NNMKCompression)
- (id)decompressedData;
- (id)compressedData;
@end

@interface NSKeyedUnarchiver (NNMKUnarchivingUtils)
+ (id)unarchiveObjectOfClasses:(id)arg1 withData:(id)arg2;
+ (id)unarchiveObjectOfClass:(Class)arg1 withData:(id)arg2;
@end

