//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftUIKit.dylib
// UUID: 607F7C19-8F78-3FEA-841C-E232F2981202
//
//                           Arch: arm64
//                Current version: 0.0.0
//          Compatibility version: 0.0.0
//                 Source version: 600.0.57.4.0
//            Minimum iOS version: 7.0.0
//                    SDK version: 8.2.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol _TtPSs9AnyObject_
@end

@interface UIActionSheet (_SwiftInterop)
- (id)initWithTitle:(id)arg1 delegate:(id)arg2 cancelButtonTitle:(id)arg3 destructiveButtonTitle:(id)arg4;
@end

@interface UIAlertView (_SwiftInterop)
- (id)initWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4;
@end

