//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libAXSafeCategoryBundle.dylib
// UUID: F3DEBC2F-6BEE-3B0F-9228-B0DB3C38A2DA
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 1541.6.25.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//
// Objective-C Garbage Collection: Unsupported
//

@interface UIAccessibilitySafeCategory : NSObject
{
}

+ (void)_addCategoryMethod:(struct objc_method *)arg1 toClass:(Class)arg2 isClass:(_Bool)arg3;
+ (id)_installSafeCategoryOnClass:(Class)arg1 isManaged:(_Bool)arg2;
+ (id)_installSafeCategoryOnClassNamed:(id)arg1 isManaged:(_Bool)arg2;
+ (void)_installSafeCategoryOnClassNamed:(id)arg1;
+ (id)_installLocalValidationMethodOnClassNamed:(id)arg1;
+ (id)_installSafeCategoryValidationMethod;
+ (id)_initializeSafeCategoryFromValidationManager;
+ (void)safeCategoryAddDependenciesToCollection:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (Class)safeCategoryTargetClass;
+ (id)safeCategoryTargetClassName;

// Remaining properties
@property(copy, nonatomic) NSString *accessibilityIdentifier; // @dynamic accessibilityIdentifier;

@end

