//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/usr/lib/libssh2.dylib
// UUID: 32CF17FB-3F8E-3495-A3FE-0C29D861A97B
//
//                           Arch: x86_64
//                Current version: 1.4.3
//          Compatibility version: 1.0.0
//                 Source version: 5.0.0.0.0
//       Minimum Mac OS X version: 10.9.0
//                    SDK version: 10.9.0
//

//
// This file does not contain any Objective-C runtime information.
//
