//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/PrivateFrameworks/iPod.framework/Versions/A/iPod
// UUID: E3E82C97-53A9-3430-82D7-4BE274DD1F87
//
//                           Arch: x86_64
//                 Source version: 20.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.10.0
//

//
// This file does not contain any Objective-C runtime information.
//
