//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/NanoResourceGrabber.framework/NanoResourceGrabber
// UUID: ACFEEF33-5BB9-3424-9637-66BB807045B9
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 47.0.0.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (_Bool)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol NanoResourceGrabberIDSXPC <NSObject>
- (void)xpcSetIcon:(NSData *)arg1 forIconVariant:(int)arg2 inBundleID:(NSString *)arg3 completion:(void (^)(void))arg4;
- (void)xpcGetCachedIconForBundleID:(NSString *)arg1 iconVariant:(int)arg2 reply:(void (^)(NSData *))arg3;
- (void)xpcGetIconForBundleID:(NSString *)arg1 iconVariant:(int)arg2 withTimeout:(double)arg3 reply:(void (^)(NSData *))arg4;
@end

@interface NanoResourceGrabber : NSObject
{
    _Bool _connectionMayBeValid;
    NSXPCConnection *_nrgdConnection;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) _Bool connectionMayBeValid; // @synthesize connectionMayBeValid=_connectionMayBeValid;
@property(retain, nonatomic) NSXPCConnection *nrgdConnection; // @synthesize nrgdConnection=_nrgdConnection;
- (void).cxx_destruct;
- (void)getCachedIconForBundleID:(id)arg1 iconVariant:(int)arg2 outIconImage:(id *)arg3;
- (void)getCachedIconForBundleID:(id)arg1 iconVariant:(int)arg2 outIconImage:(id *)arg3 outIconHash:(id *)arg4;
- (void)_getCachedIconForBundleID:(id)arg1 iconVariant:(int)arg2 reply:(CDUnknownBlockType)arg3;
- (void)setIcon:(id)arg1 forIconVariant:(int)arg2 inBundleID:(id)arg3;
- (void)_getLocalIconForBundleID:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3 withTimeout:(double)arg4;
- (void)_getRemoteIconForBundleID:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3 withTimeout:(double)arg4;
- (void)_getIconForBundleID:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3 checkLocal:(_Bool)arg4 withTimeout:(double)arg5;
- (void)getRemoteIconForBundleIDThread:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3;
- (void)getRemoteIconForBundleID:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3;
- (void)getRemoteIconForBundleIDThread:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3 timeout:(double)arg4;
- (void)getRemoteIconForBundleID:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3 timeout:(double)arg4;
- (void)getIconForBundleID:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3;
- (void)getIconForBundleIDThread:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3 timeout:(double)arg4;
- (void)getIconForBundleID:(id)arg1 iconVariant:(int)arg2 block:(CDUnknownBlockType)arg3 timeout:(double)arg4;
- (id)init;
- (void)connectToService;
- (void)dealloc;

@end

@interface NSData (MD5)
- (void)MD5:(unsigned char [16])arg1;
@end

