//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct __va_list_tag {
    unsigned int _field1;
    unsigned int _field2;
    void *_field3;
    void *_field4;
};

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CompanionSync.framework/CompanionSync
// UUID: 23554385-EA78-3148-8787-C3F8BCC49368
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 100.0.0.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol IDSServiceDelegate <NSObject>

@optional
- (void)serviceAllowedTrafficClassifiersDidReset:(IDSService *)arg1;
- (void)serviceSpaceDidBecomeAvailable:(IDSService *)arg1;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 inviteReceivedForSession:(IDSSession *)arg3 fromID:(NSString *)arg4 withContext:(NSData *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 inviteReceivedForSession:(IDSSession *)arg3 fromID:(NSString *)arg4 withOptions:(NSDictionary *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 inviteReceivedForSession:(IDSSession *)arg3 fromID:(NSString *)arg4;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 identifier:(NSString *)arg3 hasBeenDeliveredWithContext:(id)arg4;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 identifier:(NSString *)arg3 didSendWithSuccess:(_Bool)arg4 error:(NSError *)arg5;
- (void)service:(IDSService *)arg1 nearbyDevicesChanged:(NSArray *)arg2;
- (void)service:(IDSService *)arg1 devicesChanged:(NSArray *)arg2;
- (void)service:(IDSService *)arg1 activeAccountsChanged:(NSSet *)arg2;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingResourceAtURL:(NSURL *)arg3 metadata:(NSDictionary *)arg4 fromID:(NSString *)arg5 context:(IDSMessageContext *)arg6;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingResourceAtURL:(NSURL *)arg3 fromID:(NSString *)arg4 context:(IDSMessageContext *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingUnhandledProtobuf:(IDSProtobuf *)arg3 fromID:(NSString *)arg4 context:(IDSMessageContext *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingData:(NSData *)arg3 fromID:(NSString *)arg4 context:(IDSMessageContext *)arg5;
- (void)service:(IDSService *)arg1 account:(IDSAccount *)arg2 incomingMessage:(NSDictionary *)arg3 fromID:(NSString *)arg4 context:(IDSMessageContext *)arg5;
@end

@protocol NMSMessageCenterDelegate <NSObject>

@optional
- (void)messageCenter:(NMSMessageCenter *)arg1 didSuccessfullyDeliverRequestWithIdentifier:(NSString *)arg2 userInfo:(NSDictionary *)arg3;
- (void)messageCenter:(NMSMessageCenter *)arg1 didSuccessfullySendRequestWithIdentifier:(NSString *)arg2 userInfo:(NSDictionary *)arg3;
- (void)messageCenter:(NMSMessageCenter *)arg1 didResolveIDSIdentifier:(NSString *)arg2 forResponse:(NMSOutgoingResponse *)arg3;
- (void)messageCenter:(NMSMessageCenter *)arg1 didResolveIDSIdentifierForRequest:(NMSOutgoingRequest *)arg2;
- (void)messageCenter:(NMSMessageCenter *)arg1 didReceiveUnknownRequest:(NMSIncomingRequest *)arg2;
@end

@protocol NMSObfuscatableDescriptionProviding <NSObject>
- (id <NSObject>)CPObfuscatedDescriptionObject;
@end

@protocol NSCoding
- (id)initWithCoder:(NSCoder *)arg1;
- (void)encodeWithCoder:(NSCoder *)arg1;
@end

@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)arg1;
@end

@protocol NSLocking
- (void)unlock;
- (void)lock;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (_Bool)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol NSSecureCoding <NSCoding>
+ (_Bool)supportsSecureCoding;
@end

@protocol SYChangeTracking <NSObject>
- (void)deleteObject:(id <SYObject>)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)updateObject:(id <SYObject>)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)addObject:(id <SYObject>)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)deleteObject:(id <SYObject>)arg1 context:(NSDictionary *)arg2 idsOptions:(NSDictionary *)arg3;
- (void)updateObject:(id <SYObject>)arg1 context:(NSDictionary *)arg2 idsOptions:(NSDictionary *)arg3;
- (void)addObject:(id <SYObject>)arg1 context:(NSDictionary *)arg2 idsOptions:(NSDictionary *)arg3;
- (void)deleteObject:(id <SYObject>)arg1 context:(NSDictionary *)arg2;
- (void)updateObject:(id <SYObject>)arg1 context:(NSDictionary *)arg2;
- (void)addObject:(id <SYObject>)arg1 context:(NSDictionary *)arg2;
- (void)deleteObject:(id <SYObject>)arg1;
- (void)updateObject:(id <SYObject>)arg1;
- (void)addObject:(id <SYObject>)arg1;
@end

@protocol SYChangeTrackingWithErrors <SYChangeTracking>
- (_Bool)deleteObject:(id <SYObject>)arg1 context:(NSDictionary *)arg2 idsOptions:(NSDictionary *)arg3 error:(id *)arg4;
- (_Bool)updateObject:(id <SYObject>)arg1 context:(NSDictionary *)arg2 idsOptions:(NSDictionary *)arg3 error:(id *)arg4;
- (_Bool)addObject:(id <SYObject>)arg1 context:(NSDictionary *)arg2 idsOptions:(NSDictionary *)arg3 error:(id *)arg4;
- (_Bool)deleteObject:(id <SYObject>)arg1 error:(id *)arg2;
- (_Bool)updateObject:(id <SYObject>)arg1 error:(id *)arg2;
- (_Bool)addObject:(id <SYObject>)arg1 error:(id *)arg2;
@end

@protocol SYObject <NSObject>
- (NSString *)syncId;
@end

@interface SYRequestFullSync : PBCodable <NSCopying>
{
    SYMessageHeader *_header;
    NSString *_syncID;
}

@property(retain, nonatomic) NSString *syncID; // @synthesize syncID=_syncID;
@property(retain, nonatomic) SYMessageHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;

@end

@interface SYObjectChangeSet : NSObject
{
    NSMutableSet *_added;
    NSMutableSet *_updated;
    NSMutableSet *_deleted;
}

@property(copy, nonatomic) NSMutableSet *deleted; // @synthesize deleted=_deleted;
@property(copy, nonatomic) NSMutableSet *updated; // @synthesize updated=_updated;
@property(copy, nonatomic) NSMutableSet *added; // @synthesize added=_added;
- (void).cxx_destruct;
- (void)applyToStore:(id)arg1;
- (id)initWithChangesBetween:(id)arg1 and:(id)arg2;
- (id)init;
- (id)changesBetween:(id)arg1 and:(id)arg2;

@end

@interface SYLogs : NSObject
{
}

+ (_Bool)shouldLogBubblesToAggD;
+ (_Bool)shouldDisplaySyncErrorMessage;
+ (void)adjustLoggingForPrefsUpdate:(struct __CFString *)arg1;
+ (id)setupLogging:(id)arg1;
+ (id)logFolder;
+ (struct __CFString *)facility;
+ (void)initialize;

@end

@interface SYErrorInfo : PBCodable <NSCopying>
{
    unsigned int _code;
    NSString *_domain;
    NSData *_userInfo;
}

+ (void)initialize;
@property(retain, nonatomic) NSData *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) unsigned int code; // @synthesize code=_code;
@property(retain, nonatomic) NSString *domain; // @synthesize domain=_domain;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasUserInfo;
- (id)_usefulDescription;
- (id)initWithError:(id)arg1;

@end

@interface SYDictionaryObject : NSObject <SYObject, NSSecureCoding>
{
    NSDictionary *_properties;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSDictionary *properties; // @synthesize properties=_properties;
- (void).cxx_destruct;
- (id)syncId;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithProperties:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface SYChangeMessage : PBCodable <NSCopying>
{
    NSMutableArray *_changes;
    SYMessageHeader *_header;
}

@property(retain, nonatomic) NSMutableArray *changes; // @synthesize changes=_changes;
@property(retain, nonatomic) SYMessageHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)changesAtIndex:(unsigned long long)arg1;
- (unsigned long long)changesCount;
- (void)addChanges:(id)arg1;
- (void)clearChanges;

@end

@interface SYBatchSyncStart : PBCodable <NSCopying>
{
    unsigned int _estimatedChangeCount;
    SYMessageHeader *_header;
    NSString *_syncID;
    struct {
        unsigned int estimatedChangeCount:1;
    } _has;
}

@property(nonatomic) unsigned int estimatedChangeCount; // @synthesize estimatedChangeCount=_estimatedChangeCount;
@property(retain, nonatomic) NSString *syncID; // @synthesize syncID=_syncID;
@property(retain, nonatomic) SYMessageHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasEstimatedChangeCount;

@end

@interface SYRetryTimer : NSObject
{
    NSObject<OS_dispatch_source> *_timer;
    double _interval;
    double _backoffFactor;
    int _maxRetries;
    int _numRetries;
}

- (void).cxx_destruct;
- (void)cancel;
- (_Bool)incrementBackoff;
- (id)initWithInterval:(double)arg1 backoffFactor:(double)arg2 maxRetries:(int)arg3 queue:(id)arg4 callout:(CDUnknownBlockType)arg5;

@end

@interface SYChangeList : NSObject
{
    NSArray *_changes;
}

@property(readonly, nonatomic) NSArray *changes; // @synthesize changes=_changes;
- (void).cxx_destruct;
- (id)initWithChange:(id)arg1;
- (id)init;
- (id)initWithChanges:(id)arg1;

@end

@interface SYStore : NSObject <IDSServiceDelegate, NMSMessageCenterDelegate, SYChangeTrackingWithErrors>
{
    NSObject<OS_dispatch_queue> *_qosTargetQueue;
    unsigned long long _batchCounter;
    NSMutableIndexSet *_batchChunkUnackedIndices;
    _Bool _tracksChanges;
    NSMutableDictionary *_sendSignals;
    SYRetryTimer *_syncRetryTimer;
    NSObject<OS_dispatch_source> *_overflowRetryTimer;
    _Bool _deferredFullSync;
    struct {
        unsigned int delegateWillUpdate:1;
        unsigned int delegateWillUpdateWithCount:1;
        unsigned int delegateDidUpdate:1;
        unsigned int delegateDidCompleteFullSync:1;
        unsigned int delegateAllObjectsDeleted:1;
        unsigned int delegateAllObjects:1;
        unsigned int delegateShouldPerformInitialSync:1;
        unsigned int delegateBeginSyncingAllObjects:1;
        unsigned int delegateShouldDeleteOnFailedSync:1;
        unsigned int delegateErrorInFullSync:1;
        unsigned int delegateStoreEncounteredError:1;
        unsigned int delegateDidPair:1;
        unsigned int delegateDidUnpair:1;
        unsigned int delegateSentMessage:1;
        unsigned int delegatePeerProcessedMessage:1;
        unsigned int delegateSentLastSyncMessage:1;
    } _flags;
    _Bool _allowsDeletes;
    _Bool _encryptPayloads;
    _Bool _alwaysWins;
    _Bool _registeredNotificationHandlers;
    _Bool _fullSyncWasRequestedBySlave;
    id <SYStoreDelegate> _delegate;
    id <SYSerialization> _serializer;
    NSDictionary *_customIDSDeliveryOptions;
    NSString *_service;
    NSString *_databaseFileName;
    long long _priority;
    SYPersistentStore *_persistentStore;
    NSObject<OS_dispatch_queue> *_queue;
    struct __CFString *_loggingFacility;
    NSUUID *_pairedDeviceID;
    NMSMessageCenter *_messageCenter;
    SYVectorClock *_vectorClock;
    CDUnknownBlockType _nextBatchStep;
}

+ (id)fullSyncActivityDictionary;
@property(copy, nonatomic) CDUnknownBlockType nextBatchStep; // @synthesize nextBatchStep=_nextBatchStep;
@property(nonatomic) _Bool fullSyncWasRequestedBySlave; // @synthesize fullSyncWasRequestedBySlave=_fullSyncWasRequestedBySlave;
@property(retain, nonatomic) SYVectorClock *vectorClock; // @synthesize vectorClock=_vectorClock;
@property(retain, nonatomic) NMSMessageCenter *messageCenter; // @synthesize messageCenter=_messageCenter;
@property(nonatomic) _Bool registeredNotificationHandlers; // @synthesize registeredNotificationHandlers=_registeredNotificationHandlers;
@property(retain, nonatomic) NSUUID *pairedDeviceID; // @synthesize pairedDeviceID=_pairedDeviceID;
@property(nonatomic) struct __CFString *loggingFacility; // @synthesize loggingFacility=_loggingFacility;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) SYPersistentStore *persistentStore; // @synthesize persistentStore=_persistentStore;
@property(nonatomic) _Bool alwaysWins; // @synthesize alwaysWins=_alwaysWins;
@property(nonatomic) _Bool encryptPayloads; // @synthesize encryptPayloads=_encryptPayloads;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
@property(retain, nonatomic) NSString *databaseFileName; // @synthesize databaseFileName=_databaseFileName;
@property(retain, nonatomic) NSString *service; // @synthesize service=_service;
@property(nonatomic) _Bool allowsDeletes; // @synthesize allowsDeletes=_allowsDeletes;
@property(copy, nonatomic) NSDictionary *customIDSDeliveryOptions; // @synthesize customIDSDeliveryOptions=_customIDSDeliveryOptions;
@property(retain, nonatomic) id <SYSerialization> serializer; // @synthesize serializer=_serializer;
@property(nonatomic) __weak id <SYStoreDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)encodeSYObject:(id)arg1;
- (id)decodeSYObject:(id)arg1;
- (_Bool)objectChanged:(id)arg1 sinceVersion:(unsigned long long)arg2;
- (void)performFullSync;
- (void)performFullSyncToCurrentDBVersion;
- (void)performFullSyncIfNecessary;
- (void)performFullSyncIfNecessaryAskingDelegate:(_Bool)arg1;
- (void)remoteStoreRequestFullSync;
- (void)remoteStoreAllObjects:(id)arg1 fromPeer:(id)arg2 clock:(id)arg3;
- (void)setNeedsFullSyncWithContext:(id)arg1 idsOptions:(id)arg2;
- (void)setNeedsFullSync;
- (void)logChanges:(id)arg1;
- (void)sendChanges:(id)arg1 context:(id)arg2 options:(id)arg3 sentSignal:(id)arg4;
- (void)handleObjectChanges:(id)arg1 contextInfo:(id)arg2 idsOptions:(id)arg3 blockUntilSent:(_Bool)arg4 reportError:(CDUnknownBlockType)arg5;
- (void)deleteObject:(id)arg1 context:(id)arg2;
- (void)deleteObject:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)deleteObject:(id)arg1 error:(id *)arg2;
- (void)deleteObject:(id)arg1;
- (void)deleteObject:(id)arg1 context:(id)arg2 idsOptions:(id)arg3;
- (_Bool)deleteObject:(id)arg1 context:(id)arg2 idsOptions:(id)arg3 error:(id *)arg4;
- (void)updateObject:(id)arg1 context:(id)arg2;
- (void)updateObject:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)updateObject:(id)arg1 error:(id *)arg2;
- (void)updateObject:(id)arg1;
- (void)updateObject:(id)arg1 context:(id)arg2 idsOptions:(id)arg3;
- (_Bool)updateObject:(id)arg1 context:(id)arg2 idsOptions:(id)arg3 error:(id *)arg4;
- (void)addObject:(id)arg1 context:(id)arg2;
- (void)addObject:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addObject:(id)arg1;
- (_Bool)addObject:(id)arg1 error:(id *)arg2;
- (void)addObject:(id)arg1 context:(id)arg2 idsOptions:(id)arg3;
- (_Bool)addObject:(id)arg1 context:(id)arg2 idsOptions:(id)arg3 error:(id *)arg4;
- (_Bool)_allowDeltaSyncWithContext:(id)arg1 error:(id *)arg2;
- (void)_transaction:(CDUnknownBlockType)arg1 context:(id)arg2 idsOptions:(id)arg3 blockUntilSent:(_Bool)arg4 reportError:(CDUnknownBlockType)arg5;
- (void)transaction:(CDUnknownBlockType)arg1 context:(id)arg2 idsOptions:(id)arg3 blockUntilSent:(_Bool)arg4;
- (void)blockingTransaction:(CDUnknownBlockType)arg1 handlingError:(CDUnknownBlockType)arg2;
- (void)blockingTransaction:(CDUnknownBlockType)arg1;
- (void)transaction:(CDUnknownBlockType)arg1 context:(id)arg2 idsOptions:(id)arg3;
- (void)transaction:(CDUnknownBlockType)arg1 context:(id)arg2;
- (void)transaction:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)transaction:(CDUnknownBlockType)arg1 handlingError:(CDUnknownBlockType)arg2;
- (void)transaction:(CDUnknownBlockType)arg1;
- (id)newMessageHeader;
- (void)sendMessage:(id)arg1 ofType:(unsigned short)arg2 respondingTo:(id)arg3 userInfo:(id)arg4 idsOptions:(id)arg5;
- (id)wrapMessage:(id)arg1 ofType:(unsigned short)arg2 respondingTo:(id)arg3 userInfo:(id)arg4;
- (void)messageCenter:(id)arg1 didSuccessfullyDeliverRequestWithIdentifier:(id)arg2 userInfo:(id)arg3;
- (void)messageCenter:(id)arg1 didSuccessfullySendRequestWithIdentifier:(id)arg2 userInfo:(id)arg3;
- (void)messageCenter:(id)arg1 didResolveIDSIdentifier:(id)arg2 forResponse:(id)arg3;
- (void)messageCenter:(id)arg1 didResolveIDSIdentifierForRequest:(id)arg2;
- (void)messageCenter:(id)arg1 didReceiveUnknownRequest:(id)arg2;
- (void)handleChangeMessage:(id)arg1;
- (void)handleBatchSyncEnd:(id)arg1 response:(id)arg2;
- (void)handleBatchSyncChunk:(id)arg1 response:(id)arg2;
- (void)handleBatchSyncStart:(id)arg1;
- (void)handleSyncAllObjects:(id)arg1 response:(id)arg2;
- (void)_syncEndedWithSyncID:(id)arg1;
- (_Bool)_shouldSkipNonSyncMessages;
- (_Bool)_shouldIgnoreSyncID:(id)arg1;
- (void)handleFullSyncRequest:(id)arg1 response:(id)arg2;
- (_Bool)peerState:(id)arg1 fromPeer:(id)arg2 matchesExpectationForChangeCount:(unsigned long long)arg3 offsetAmount:(unsigned long long *)arg4;
- (void)_copyPeerClockFromMessageHeaderIfNecessary:(id)arg1;
- (void)postUserNotification:(id)arg1 message:(id)arg2;
- (_Bool)inFullSync;
@property(nonatomic) double timeToLive;
- (void)setupDatabase;
- (void)_setupMessageCenter_LOCKED;
- (void)setupMessageCenter;
- (void)_handleIDSOverflow;
- (void)_recordLastSeqNo:(id)arg1;
- (_Bool)_checkMessageHeader:(id)arg1 messageID:(id)arg2;
- (id)_pathForMessageCenterCache;
- (void)_vectorClockUpdated;
- (void)_devicePaired:(id)arg1;
- (void)_deviceUnpaired:(id)arg1;
- (_Bool)_isUsingGenericCache;
- (_Bool)_isPairedWithDevice:(id)arg1;
@property(readonly, nonatomic) _Bool hasCompletedFullSync;
@property(nonatomic) long long maxBytesInFlight;
@property(readonly, nonatomic) long long state;
@property(nonatomic) unsigned int deliveryQOS;
@property(readonly, nonatomic, getter=isPaired) _Bool paired;
- (void)setupPairingNotifications;
- (void)_listenForPrefsChangeNotifications;
- (void)_updateMessageCenterPrefs:(id)arg1;
- (void)_prefsChanged;
- (id)_batchChunkUnackedIndices;
- (void)dealloc;
- (id)initWithService:(id)arg1 isGStore:(_Bool)arg2 priority:(long long)arg3 isMasterStore:(_Bool)arg4 tracksChanges:(_Bool)arg5;
- (id)initWithService:(id)arg1 isGStore:(_Bool)arg2 highPriority:(_Bool)arg3 isMasterStore:(_Bool)arg4 tracksChanges:(_Bool)arg5;
- (id)initWithService:(id)arg1 isGStore:(_Bool)arg2 priority:(long long)arg3 isMasterStore:(_Bool)arg4;
- (id)initWithService:(id)arg1 isGStore:(_Bool)arg2 highPriority:(_Bool)arg3 isMasterStore:(_Bool)arg4;
- (id)initWithService:(id)arg1 isGStore:(_Bool)arg2 highPriority:(_Bool)arg3;
- (id)initWithService:(id)arg1;
- (id)initWithBundleIdentifier:(id)arg1 isGStore:(_Bool)arg2 highPriority:(_Bool)arg3;
- (id)initWithBundleIdentifier:(id)arg1;
- (void)_retrySync;
- (id)newFullSyncContext;
- (void)processBatchChunkAck:(unsigned int)arg1;
- (void)processBatchChunkAtIndex:(unsigned int)arg1 encodedObjects:(id)arg2 error:(id *)arg3;
- (void)processBatchSyncEnd:(unsigned long long)arg1;
- (void)processBatchSyncStart;
- (_Bool)performBatchedSyncToCurrentDBVersion;
- (void)_sendBatchChunk:(id)arg1 withState:(id)arg2 then:(CDUnknownBlockType)arg3;
- (void)_restartBatchSyncWithState:(id)arg1 then:(CDUnknownBlockType)arg2;
- (void)_postBatchEndMessageWithState:(id)arg1 error:(id)arg2 then:(CDUnknownBlockType)arg3;
- (void)_postBatchStartMessageWithState:(id)arg1 then:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) _Bool inDeltaSync;
- (void)didEndDeltaSync;
- (void)willBeginDeltaSync;
@property(nonatomic) _Bool tracksChanges;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NMSWindowData : NSObject
{
    NSString *_path;
    struct __CFString *_loggingFacility;
    NSObject<OS_dispatch_queue> *_syncQ;
    struct sqlite3 *_db;
    struct sqlite3_stmt *_addMessageInFlight;
    struct sqlite3_stmt *_getMessageLength;
    struct sqlite3_stmt *_removeMessageInFlight;
    struct sqlite3_stmt *_getNextExpireDate;
    struct sqlite3_stmt *_getExpiredMessageIDs;
    struct sqlite3_stmt *_getBytesInFlight;
    struct sqlite3_stmt *_getCountInFlight;
    struct sqlite3_stmt *_pushPendingMessage;
    struct sqlite3_stmt *_getPendingMessage;
    struct sqlite3_stmt *_popPendingMessage;
    struct sqlite3_stmt *_countPendingMessages;
}

- (void).cxx_destruct;
- (struct sqlite3 *)dbRef;
@property(readonly, nonatomic) unsigned long long countOfPendingMessages;
- (id)popPendingMessage;
- (void)pushPendingMessageData:(id)arg1 timeToLive:(double)arg2;
@property(readonly, nonatomic) NSDate *dateOfNextMessageExpiry;
@property(readonly, nonatomic) unsigned long long countOfAllMessagesInFlight;
@property(readonly, nonatomic) unsigned long long lengthOfAllMessagesInFlight;
@property(readonly, nonatomic) NSArray *expiredMessageIDs;
- (unsigned long long)removeAndReturnLengthOfMessagesWithIDs:(id)arg1;
- (unsigned long long)removeAndReturnLengthOfMessageWithID:(id)arg1;
- (void)addMessageWithID:(id)arg1 ofLength:(unsigned long long)arg2 timeoutTime:(double)arg3;
- (void)removeAllMessages;
- (_Bool)_syncTransaction:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (_Bool)_openDBForceRecreate:(_Bool)arg1;
- (int)_getSchemaVersion;
- (void)dealloc;
- (id)initWithPath:(id)arg1 logFacility:(struct __CFString *)arg2;
- (id)init;

@end

@interface SYMessageHeader : PBCodable <NSCopying>
{
    unsigned long long _sequenceNumber;
    double _timestamp;
    SYPeer *_sender;
    SYVectorClock *_state;
    unsigned int _version;
}

@property(nonatomic) unsigned long long sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
@property(retain, nonatomic) SYVectorClock *state; // @synthesize state=_state;
@property(retain, nonatomic) SYPeer *sender; // @synthesize sender=_sender;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;

@end

@interface SYPersistentStore : NSObject
{
    NSString *_path;
    struct __CFString *_loggingFacility;
    double _timeToLiveCache;
    _Bool _changeTrackingEnabled;
    NSMutableDictionary *_peerSeqnoSets;
    NSObject<OS_dispatch_queue> *_syncQ;
    struct sqlite3 *_db;
    struct sqlite3_stmt *_getInFullSync;
    struct sqlite3_stmt *_getChangeCount;
    struct sqlite3_stmt *_getNextExpireTime;
    struct sqlite3_stmt *_purgeExpiredChanges;
    struct sqlite3_stmt *_insertChange;
    struct sqlite3_stmt *_getFullsyncSent;
    struct sqlite3_stmt *_setFullsyncSent;
    struct sqlite3_stmt *_logSyncComplete;
    struct sqlite3_stmt *_getChangeIDsSinceVersion;
    struct sqlite3_stmt *_getLocalVersion;
    struct sqlite3_stmt *_getOldestVersion;
    struct sqlite3_stmt *_setVectorClock;
    struct sqlite3_stmt *_setPeerSeqNo;
    struct sqlite3_stmt *_getPeerSeqNo;
    struct sqlite3_stmt *_setPeerSeqNoSet;
    struct sqlite3_stmt *_enterFullSync;
    struct sqlite3_stmt *_exitFullSync;
    struct sqlite3_stmt *_getIgnoringSyncID;
    struct sqlite3_stmt *_getCurrentSyncID;
    struct sqlite3_stmt *_getCurrentSyncStartTime;
    struct sqlite3_stmt *_getLastEndedSyncID;
    struct sqlite3_stmt *_getWaitingForSyncID;
    struct sqlite3_stmt *_setWaitingForSyncID;
    struct sqlite3_stmt *_setAllSentForSyncID;
    struct sqlite3_stmt *_getAllSentForCurrentSync;
    struct sqlite3_stmt *_getLastSyncError;
    struct sqlite3_stmt *_setSyncUserInfo;
    struct sqlite3_stmt *_getSyncUserInfo;
    struct sqlite3_stmt *_setSyncIDSOptions;
    struct sqlite3_stmt *_getSyncIDSOptions;
    _Bool _cachedVersionStale;
    NSString *_peerID;
    double _unfinishedSyncTimeout;
    NSSet *_cachedChangedSyncIDs;
    unsigned long long _cachedChangedSyncIDsVersion;
}

@property(nonatomic) _Bool cachedVersionStale; // @synthesize cachedVersionStale=_cachedVersionStale;
@property(nonatomic) unsigned long long cachedChangedSyncIDsVersion; // @synthesize cachedChangedSyncIDsVersion=_cachedChangedSyncIDsVersion;
@property(retain, nonatomic) NSSet *cachedChangedSyncIDs; // @synthesize cachedChangedSyncIDs=_cachedChangedSyncIDs;
@property(nonatomic) double unfinishedSyncTimeout; // @synthesize unfinishedSyncTimeout=_unfinishedSyncTimeout;
@property(readonly, nonatomic) NSString *peerID; // @synthesize peerID=_peerID;
- (void).cxx_destruct;
- (void)changeTrackingToggled:(_Bool)arg1;
- (void)clearAllChanges;
- (_Bool)objectChanged:(id)arg1 sinceVersion:(unsigned long long)arg2;
- (unsigned long long)_oldestVersion;
- (_Bool)logSyncCompletionToRemoteVersion:(unsigned long long)arg1;
- (_Bool)logChanges:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) unsigned long long lastSeenRemoteVersion;
@property(readonly, nonatomic) unsigned long long currentLocalVersion;
@property(readonly, nonatomic) double durationOfLastFullSync;
@property(nonatomic) _Bool completedSync;
@property(copy, nonatomic) NSDictionary *fullSyncIDSOptions;
@property(copy, nonatomic) NSDictionary *fullSyncUserInfo;
@property(copy, nonatomic) NSString *waitingForSyncEndID;
@property(readonly, nonatomic) NSString *lastSyncEndID;
@property(readonly, nonatomic) _Bool inFullSync;
@property(readonly, nonatomic) NSString *currentFullSyncID;
@property(readonly, nonatomic) NSError *lastSyncError;
@property(readonly, nonatomic) _Bool lastSyncFailed;
@property(readonly, nonatomic) _Bool currentSyncSendComplete;
- (void)sendCompletedForSyncWithID:(id)arg1;
- (_Bool)ignoringFullSyncWithID:(id)arg1;
- (_Bool)reassignCurrentSyncID:(id)arg1;
- (void)exitFullSyncWithID:(id)arg1 error:(id)arg2;
- (void)enterFullSyncWithID:(id)arg1 ignoring:(_Bool)arg2;
@property(readonly, nonatomic) _Bool canStartNewSyncSession;
@property(copy, nonatomic) NSDate *lastMessageReceived;
@property(copy, nonatomic) NSDate *overflowResyncTime;
@property(retain, nonatomic) NSString *vectorClockJSON;
@property(readonly, nonatomic) unsigned long long changeCount;
@property(nonatomic) double timeToLive;
@property(readonly, nonatomic) NSString *path;
@property(nonatomic, getter=isPerformingDeltaSync) _Bool performingDeltaSync;
- (void)resetSequenceNumbersForPeer:(id)arg1;
- (_Bool)sequenceNumberIsDuplicate:(unsigned long long)arg1 forPeer:(id)arg2;
- (unsigned long long)lastSequenceNumberForPeerID:(id)arg1;
- (unsigned long long)_lastSequenceNumberForPeerID_LOCKED:(id)arg1;
- (void)setLastSequenceNumber:(unsigned long long)arg1 fromPeer:(id)arg2;
- (unsigned long long)nextSequenceNumber;
- (void)_cacheTTL;
- (void)_storeSequenceNumberSet:(id)arg1 forPeerID:(id)arg2;
- (id)_sequenceNumberSetForPeerID:(id)arg1;
- (id)_decodeIndexSet:(id)arg1;
- (id)_encodeIndexSet:(id)arg1;
- (void)_fixPeerInfo;
- (_Bool)_inTransaction:(_Bool)arg1 do:(CDUnknownBlockType)arg2;
- (void)_convertTimestamps;
- (_Bool)_openDBAtPath:(id)arg1;
- (int)_getSchemaVersion;
- (_Bool)_tableEmpty:(id)arg1;
- (struct sqlite3 *)_dbRef;
- (void)dealloc;
- (id)initWithPath:(id)arg1 loggingFacility:(struct __CFString *)arg2 changeTrackingEnabled:(_Bool)arg3;

@end

@interface SYBatchSyncEnd : PBCodable <NSCopying>
{
    SYErrorInfo *_error;
    SYMessageHeader *_header;
    NSString *_syncID;
}

@property(retain, nonatomic) SYErrorInfo *error; // @synthesize error=_error;
@property(retain, nonatomic) NSString *syncID; // @synthesize syncID=_syncID;
@property(retain, nonatomic) SYMessageHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasError;

@end

@interface SYTransaction : NSObject <SYChangeTracking>
{
    NSDictionary *_contextInfo;
    NSDictionary *_idsOptions;
    CDUnknownBlockType _completion;
    SYStore *_store;
    NSMutableArray *_changes;
}

@property(retain, nonatomic) NSMutableArray *changes; // @synthesize changes=_changes;
@property(retain, nonatomic) SYStore *store; // @synthesize store=_store;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(copy, nonatomic) NSDictionary *idsOptions; // @synthesize idsOptions=_idsOptions;
@property(copy, nonatomic) NSDictionary *contextInfo; // @synthesize contextInfo=_contextInfo;
- (void).cxx_destruct;
- (void)rollback;
- (void)commitBlocking:(_Bool)arg1 reportError:(CDUnknownBlockType)arg2;
- (void)commit;
- (void)deleteObject:(id)arg1 context:(id)arg2 idsOptions:(id)arg3;
- (void)updateObject:(id)arg1 context:(id)arg2 idsOptions:(id)arg3;
- (void)addObject:(id)arg1 context:(id)arg2 idsOptions:(id)arg3;
- (void)deleteObject:(id)arg1 context:(id)arg2;
- (void)updateObject:(id)arg1 context:(id)arg2;
- (void)addObject:(id)arg1 context:(id)arg2;
- (void)deleteObject:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateObject:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addObject:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)deleteObject:(id)arg1;
- (void)updateObject:(id)arg1;
- (void)addObject:(id)arg1;
- (id)initWithStore:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NMSObfuscatableDescriptionItem : NSObject
{
    _Bool _obfuscated;
    NSString *_format;
    id <NSObject> _value;
}

@property(nonatomic) _Bool obfuscated; // @synthesize obfuscated=_obfuscated;
@property(retain, nonatomic) id <NSObject> value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *format; // @synthesize format=_format;
- (void).cxx_destruct;
- (id)initWithFormat:(id)arg1 value:(id)arg2 obfuscated:(_Bool)arg3;

@end

@interface NMSObfuscatableDescription : NSObject
{
    NSString *_prefixString;
    NSMutableArray *_items;
}

@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(retain, nonatomic) NSString *prefixString; // @synthesize prefixString=_prefixString;
- (void).cxx_destruct;
- (id)CPSafeDescription;
- (id)description;
- (id)_descriptionObfuscated:(_Bool)arg1;
- (void)addObfuscatedDescriptionFormat:(id)arg1 value:(id)arg2;
- (void)addDescriptionFormat:(id)arg1 value:(id)arg2;
- (id)init;

@end

@interface SYBatchChunkAck : PBCodable <NSCopying>
{
    unsigned int _chunkIndex;
    SYErrorInfo *_error;
    SYMessageHeader *_header;
    NSString *_syncID;
}

@property(retain, nonatomic) SYErrorInfo *error; // @synthesize error=_error;
@property(nonatomic) unsigned int chunkIndex; // @synthesize chunkIndex=_chunkIndex;
@property(retain, nonatomic) NSString *syncID; // @synthesize syncID=_syncID;
@property(retain, nonatomic) SYMessageHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasError;

@end

@interface NMSPersistentDictionary : NSObject <NSLocking>
{
    Class _objectClass;
    NSString *_path;
    struct __CFString *_loggingFacility;
    NSObject<OS_dispatch_semaphore> *_lock;
    struct sqlite3 *_db;
    struct sqlite3_stmt *_fetch;
    struct sqlite3_stmt *_insert;
    struct sqlite3_stmt *_reset;
    struct sqlite3_stmt *_remove;
    struct sqlite3_stmt *_removeAll;
    struct sqlite3_stmt *_byDate;
}

- (void).cxx_destruct;
- (void)enumerateObjectsSortedByExpirationDate:(CDUnknownBlockType)arg1;
- (void)removeAllObjects;
- (void)resetObject:(id)arg1 forKey:(id)arg2;
- (void)removeObjectForKey:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2 expires:(id)arg3;
- (id)_dataFromObject:(id)arg1;
- (id)_objectFromData:(id)arg1;
- (void)_openDBForceRecreate:(_Bool)arg1;
- (void)unlock;
- (void)lock;
- (void)dealloc;
- (id)initWithPath:(id)arg1 objectClass:(Class)arg2 loggingFacility:(struct __CFString *)arg3;
- (id)init;

@end

@interface SYFullSyncRequestAck : PBCodable <NSCopying>
{
    SYErrorInfo *_error;
    SYMessageHeader *_header;
    NSString *_inProgressSyncID;
    NSString *_requestSyncID;
    _Bool _accepted;
}

@property(retain, nonatomic) NSString *inProgressSyncID; // @synthesize inProgressSyncID=_inProgressSyncID;
@property(retain, nonatomic) SYErrorInfo *error; // @synthesize error=_error;
@property(nonatomic) _Bool accepted; // @synthesize accepted=_accepted;
@property(retain, nonatomic) NSString *requestSyncID; // @synthesize requestSyncID=_requestSyncID;
@property(retain, nonatomic) SYMessageHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasInProgressSyncID;
@property(readonly, nonatomic) _Bool hasError;

@end

@interface _NMSDispatchQueue : NSObject
{
    NSObject<OS_dispatch_queue> *_q;
    int _r;
}

- (void).cxx_destruct;
- (void)async:(CDUnknownBlockType)arg1;
- (void)sync:(CDUnknownBlockType)arg1;
- (void)resume;
- (void)suspend;
@property(readonly, nonatomic, getter=isSuspended) _Bool suspended;
- (void)setTarget:(id)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1 attributes:(id)arg2;
- (id)init;

@end

@interface NMSMessageCenter : NSObject <IDSServiceDelegate>
{
    NSString *_serviceIdentifier;
    NSString *_launchNotification;
    struct __CFString *_loggingFacility;
    IDSService *_service;
    NSMutableDictionary *_requestHandlers;
    NSMutableDictionary *_errorHandlers;
    NSMutableDictionary *_responseHandlers;
    NSMutableDictionary *_pbMapping;
    NMSPersistentDictionary *_persistentContextStore;
    NSDate *_nextExpireTimerFireDate;
    NSObject<OS_dispatch_source> *_expireTimer;
    unsigned long long _currentBytesInFlight;
    NMSWindowData *_windowData;
    NSObject<OS_dispatch_source> *_windowTimeout;
    _NMSDispatchQueue *_windowQueue;
    _Bool _enableTransmissionWindow;
    _Bool _delegateRequiresACKs;
    id <NMSMessageCenterDelegate> _delegate;
    unsigned long long _maxMessagesInFlight;
    unsigned long long _minMessagesInFlight;
    unsigned long long _maxBytesInFlight;
    double _windowResponseTimeout;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (void)setMessageWindowCountEnabled:(_Bool)arg1;
+ (_Bool)messageWindowCountEnabled;
@property(nonatomic) _Bool delegateRequiresACKs; // @synthesize delegateRequiresACKs=_delegateRequiresACKs;
@property(retain, nonatomic) IDSService *service; // @synthesize service=_service;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) double windowResponseTimeout; // @synthesize windowResponseTimeout=_windowResponseTimeout;
@property(nonatomic) unsigned long long maxBytesInFlight; // @synthesize maxBytesInFlight=_maxBytesInFlight;
@property(nonatomic) unsigned long long minMessagesInFlight; // @synthesize minMessagesInFlight=_minMessagesInFlight;
@property(nonatomic) unsigned long long maxMessagesInFlight; // @synthesize maxMessagesInFlight=_maxMessagesInFlight;
@property(nonatomic) _Bool enableTransmissionWindow; // @synthesize enableTransmissionWindow=_enableTransmissionWindow;
@property(nonatomic) __weak id <NMSMessageCenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)service:(id)arg1 account:(id)arg2 incomingData:(id)arg3 fromID:(id)arg4 context:(id)arg5;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 hasBeenDeliveredWithContext:(id)arg4;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5;
- (void)_obliterate;
- (void)_handleError:(id)arg1 context:(id)arg2;
- (void)_sendResponse:(id)arg1;
- (void)sendRequest:(id)arg1;
- (id)_decodeIncomingRequestData:(id)arg1 context:(id)arg2;
- (id)_buildDataForResponse:(id)arg1 options:(id *)arg2;
- (id)_buildDataForRequest:(id)arg1 options:(id *)arg2;
- (void)dropExtantMessages;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *actionQ;
@property(readonly, nonatomic) IDSService *idsService;
- (void)resume;
- (void)_updateExpireTimerWithDate:(id)arg1;
- (void)_expireMessages;
@property(readonly, nonatomic, getter=_currentBytesInFlight) unsigned long long currentBytesInFlight;
- (id)_pbMappingForMessageID:(unsigned short)arg1;
- (void)mapPBRequest:(Class)arg1 toResponse:(Class)arg2 messageID:(unsigned short)arg3;
- (void)addResponseHandler:(unsigned short)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)addErrorHandlerForMessageID:(unsigned short)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)addRequestHandlerForMessageID:(unsigned short)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)setDelegate:(id)arg1 queue:(id)arg2;
- (id)responseHandlers;
- (id)errorHandlers;
- (id)requestHandlers;
- (void)_timeoutWindowedMessages;
- (void)_setNextWindowTimeoutFireDate;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithIDSServiceIdentifier:(id)arg1 launchOnDemandNotification:(id)arg2 cacheFolderPath:(id)arg3 loggingFacility:(struct __CFString *)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NMSOutgoingRequest : NSObject <NMSObfuscatableDescriptionProviding>
{
    _Bool _shouldEncrypt;
    unsigned short _messageID;
    NSData *_data;
    NSString *_idsIdentifier;
    unsigned long long _priority;
    double _sendTimeout;
    double _responseTimeout;
    NSDictionary *_persistentUserInfo;
    NSDictionary *_extraIDSOptions;
    NMSMessageCenter *_messageCenter;
    id _pbRequest;
}

+ (id)requestWithMessageID:(unsigned short)arg1;
@property(retain, nonatomic) id pbRequest; // @synthesize pbRequest=_pbRequest;
@property(nonatomic) __weak NMSMessageCenter *messageCenter; // @synthesize messageCenter=_messageCenter;
@property(retain, nonatomic) NSDictionary *extraIDSOptions; // @synthesize extraIDSOptions=_extraIDSOptions;
@property(retain, nonatomic) NSDictionary *persistentUserInfo; // @synthesize persistentUserInfo=_persistentUserInfo;
@property(nonatomic) _Bool shouldEncrypt; // @synthesize shouldEncrypt=_shouldEncrypt;
@property(nonatomic) double responseTimeout; // @synthesize responseTimeout=_responseTimeout;
@property(nonatomic) double sendTimeout; // @synthesize sendTimeout=_sendTimeout;
@property(nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(copy, nonatomic) NSString *idsIdentifier; // @synthesize idsIdentifier=_idsIdentifier;
@property(nonatomic) unsigned short messageID; // @synthesize messageID=_messageID;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)CPObfuscatedDescriptionObject;
@property(readonly, copy) NSString *description;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NMSIncomingRequest : NSObject <NMSObfuscatableDescriptionProviding>
{
    _Bool _expectsResponse;
    unsigned short _messageID;
    NMSMessageCenter *_messageCenter;
    NSString *_idsIdentifier;
    NSData *_data;
    unsigned long long _priority;
    NMSOutgoingResponse *_response;
    id _pbRequest;
}

+ (void)setAllowsUnrepliedRequestsForUnitTesting:(_Bool)arg1;
+ (_Bool)allowsUnrepliedRequestsForUnitTesting;
@property(retain, nonatomic) id pbRequest; // @synthesize pbRequest=_pbRequest;
@property(retain, nonatomic) NMSOutgoingResponse *response; // @synthesize response=_response;
@property(nonatomic) _Bool expectsResponse; // @synthesize expectsResponse=_expectsResponse;
@property(nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(copy, nonatomic) NSString *idsIdentifier; // @synthesize idsIdentifier=_idsIdentifier;
@property(nonatomic) unsigned short messageID; // @synthesize messageID=_messageID;
@property(nonatomic) __weak NMSMessageCenter *messageCenter; // @synthesize messageCenter=_messageCenter;
- (void).cxx_destruct;
- (id)CPObfuscatedDescriptionObject;
@property(readonly, copy) NSString *description;
- (void)configureResponse;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NMSIncomingResponse : NSObject <NMSObfuscatableDescriptionProviding>
{
    unsigned short _messageID;
    NSData *_data;
    NSString *_idsIdentifier;
    NSString *_requestIDSIdentifier;
    NSDate *_requestSent;
    NSDictionary *_requestPersistentUserInfo;
    id _pbResponse;
}

@property(retain, nonatomic) id pbResponse; // @synthesize pbResponse=_pbResponse;
@property(retain, nonatomic) NSDictionary *requestPersistentUserInfo; // @synthesize requestPersistentUserInfo=_requestPersistentUserInfo;
@property(retain, nonatomic) NSDate *requestSent; // @synthesize requestSent=_requestSent;
@property(copy, nonatomic) NSString *requestIDSIdentifier; // @synthesize requestIDSIdentifier=_requestIDSIdentifier;
@property(copy, nonatomic) NSString *idsIdentifier; // @synthesize idsIdentifier=_idsIdentifier;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(nonatomic) unsigned short messageID; // @synthesize messageID=_messageID;
- (void).cxx_destruct;
- (id)CPObfuscatedDescriptionObject;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NMSOutgoingResponse : NSObject <NMSObfuscatableDescriptionProviding>
{
    _Bool _sent;
    NMSIncomingRequest *_request;
    NSData *_data;
    unsigned long long _priority;
    double _sendTimeout;
    NSDictionary *_persistentUserInfo;
    NSDictionary *_extraIDSOptions;
    NSString *_idsIdentifier;
    id _pbResponse;
}

@property(retain, nonatomic) id pbResponse; // @synthesize pbResponse=_pbResponse;
@property(copy, nonatomic) NSString *idsIdentifier; // @synthesize idsIdentifier=_idsIdentifier;
@property(getter=isSent) _Bool sent; // @synthesize sent=_sent;
@property(retain, nonatomic) NSDictionary *extraIDSOptions; // @synthesize extraIDSOptions=_extraIDSOptions;
@property(retain, nonatomic) NSDictionary *persistentUserInfo; // @synthesize persistentUserInfo=_persistentUserInfo;
@property(nonatomic) double sendTimeout; // @synthesize sendTimeout=_sendTimeout;
@property(nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(nonatomic) __weak NMSIncomingRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (id)CPObfuscatedDescriptionObject;
@property(readonly, copy) NSString *description;
- (void)send;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NMSPBMapping : NSObject
{
    Class _requestClass;
    Class _responseClass;
}

@property(retain, nonatomic) Class responseClass; // @synthesize responseClass=_responseClass;
@property(retain, nonatomic) Class requestClass; // @synthesize requestClass=_requestClass;
- (void).cxx_destruct;
- (id)description;

@end

@interface NMSMessagePersistentContext : NSObject <NSSecureCoding>
{
    _Bool _fromRequest;
    _Bool _sendAcked;
    _Bool _processAcked;
    unsigned short _messageID;
    NSString *_idsIdentifier;
    NSDictionary *_userInfo;
    NSDictionary *_customIDSFlags;
    NSDate *_date;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) _Bool processAcked; // @synthesize processAcked=_processAcked;
@property(nonatomic) _Bool sendAcked; // @synthesize sendAcked=_sendAcked;
@property(nonatomic, getter=isFromRequest) _Bool fromRequest; // @synthesize fromRequest=_fromRequest;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSDictionary *customIDSFlags; // @synthesize customIDSFlags=_customIDSFlags;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(copy, nonatomic) NSString *idsIdentifier; // @synthesize idsIdentifier=_idsIdentifier;
@property(nonatomic) unsigned short messageID; // @synthesize messageID=_messageID;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

@interface SYClock : PBCodable <NSCopying>
{
    unsigned long long _version;
    SYPeer *_peer;
}

+ (void)initialize;
@property(nonatomic) unsigned long long version; // @synthesize version=_version;
@property(retain, nonatomic) SYPeer *peer; // @synthesize peer=_peer;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)_myDescription;
- (unsigned long long)increment;
- (unsigned long long)increaseBy:(unsigned long long)arg1;

@end

@interface SYChange : PBCodable <NSCopying>
{
    unsigned long long _version;
    NSData *_data;
    NSString *_objectId;
    int _type;
}

+ (id)changeWithObject:(id)arg1 updateType:(int)arg2 store:(id)arg3;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(nonatomic) unsigned long long version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *objectId; // @synthesize objectId=_objectId;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasData;
- (id)objectForStore:(id)arg1;

@end

@interface SYBatchSyncChunk : PBCodable <NSCopying>
{
    unsigned int _chunkIndex;
    SYMessageHeader *_header;
    NSMutableArray *_objects;
    NSString *_syncID;
}

@property(retain, nonatomic) NSMutableArray *objects; // @synthesize objects=_objects;
@property(nonatomic) unsigned int chunkIndex; // @synthesize chunkIndex=_chunkIndex;
@property(retain, nonatomic) NSString *syncID; // @synthesize syncID=_syncID;
@property(retain, nonatomic) SYMessageHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)objectsAtIndex:(unsigned long long)arg1;
- (unsigned long long)objectsCount;
- (void)addObjects:(id)arg1;
- (void)clearObjects;

@end

@interface SYDeletedObject : NSObject <SYObject>
{
    NSString *_syncId;
}

@property(retain, nonatomic) NSString *syncId; // @synthesize syncId=_syncId;
- (void).cxx_destruct;
- (id)initWithSyncId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface SYTransportLog : NSObject
{
    NSString *_rootPath;
    NSString *_facility;
}

+ (id)sharedInstance;
+ (id)_logPath;
@property(copy, nonatomic) NSString *facility; // @synthesize facility=_facility;
- (void).cxx_destruct;
- (void)_logMessage:(id)arg1 file:(const char *)arg2 line:(int)arg3 function:(const char *)arg4;
- (void)logMessage:(id)arg1 args:(struct __va_list_tag [1])arg2;
- (void)logMessage:(id)arg1;
- (id)_setupLog;
- (_Bool)_ensureFolder;
- (id)init;

@end

@interface SYStatisticStore : NSObject
{
    NSString *_path;
    struct sqlite3 *_db;
    struct sqlite3_stmt *_insertIncoming;
    struct sqlite3_stmt *_addProcessingTimeIncoming;
    struct sqlite3_stmt *_addErrorIncoming;
    struct sqlite3_stmt *_markCompleteIncoming;
    struct sqlite3_stmt *_insertOutgoing;
    struct sqlite3_stmt *_updateOutgoingIdentifier;
    struct sqlite3_stmt *_updateOutgoing;
    struct sqlite3_stmt *_timestampForID;
    struct sqlite3_stmt *_reserveRowID;
    struct sqlite3_stmt *_responseReceived;
    struct sqlite3_stmt *_requestAcked;
    long long _lastIncomingRowID;
    NSObject<OS_dispatch_queue> *_operations_queue;
}

+ (id)sharedInstance;
+ (id)unpackMessageData:(id)arg1;
- (void).cxx_destruct;
- (void)confirmDeliveryOfOutgoingMessage:(id)arg1;
- (void)updateOutgoingMessageWithIdentifier:(id)arg1 didReceiveResponse:(_Bool)arg2 error:(id)arg3;
- (void)updateOutgoingMessageWithIdentifier:(id)arg1 forService:(id)arg2 sentSuccessfully:(_Bool)arg3 sendError:(id)arg4;
- (void)assignIdentifier:(id)arg1 toOutgoingMessage:(id)arg2;
- (void)recordOutgoingMessage:(id)arg1 forService:(id)arg2;
- (void)markLastIncomingMessageComplete;
- (void)updateLastIncomingMessageWithError:(id)arg1;
- (void)updateLastIncomingMessageWithProcessingTime:(double)arg1;
- (void)recordIncomingMessage:(id)arg1 forService:(id)arg2;
- (id)_unpackMessageData:(id)arg1;
- (void)_unpackPBResponse:(id)arg1 forMessageID:(unsigned short)arg2 intoDictionary:(id)arg3;
- (void)_unpackPBRequest:(id)arg1 forMessageID:(unsigned short)arg2 intoDictionary:(id)arg3;
- (id)_keySetForMessageLogTable;
- (double)_getMachTimestamp;
- (void)_openDB;
- (int)_getSchemaVersion;
- (_Bool)_openDBFile:(_Bool)arg1;
- (void)_ensureCorrectFileOwnership:(id)arg1;
- (_Bool)_tableEmpty:(id)arg1;
- (void)dealloc;
- (id)initWithPath:(id)arg1;
- (id)init;
- (id)operationQ;
- (struct sqlite3 *)dbRef;

@end

@interface SYSyncEndResponse : PBCodable <NSCopying>
{
    SYErrorInfo *_error;
    int _errorResolution;
    SYMessageHeader *_header;
    NSString *_syncID;
    struct {
        unsigned int errorResolution:1;
    } _has;
}

@property(retain, nonatomic) SYErrorInfo *error; // @synthesize error=_error;
@property(retain, nonatomic) NSString *syncID; // @synthesize syncID=_syncID;
@property(retain, nonatomic) SYMessageHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasErrorResolution;
@property(nonatomic) int errorResolution; // @synthesize errorResolution=_errorResolution;
@property(readonly, nonatomic) _Bool hasError;

@end

@interface SYVectorClock : PBCodable <NSCopying>
{
    NSMutableArray *_clocks;
}

+ (void)initialize;
@property(retain, nonatomic) NSMutableArray *clocks; // @synthesize clocks=_clocks;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)clocksAtIndex:(unsigned long long)arg1;
- (unsigned long long)clocksCount;
- (void)addClocks:(id)arg1;
- (void)clearClocks;
- (_Bool)_setTheory_isEqual:(id)arg1;
- (id)jsonRepresentation;
- (id)compactDictionaryRepresentation;
- (void)setClockValue:(unsigned long long)arg1 forPeerID:(id)arg2;
- (void)incrementClockForPeerID:(id)arg1;
- (void)increaseClockForPeerID:(id)arg1 by:(unsigned long long)arg2;
- (unsigned long long)clockValueForPeerID:(id)arg1;
- (void)setClockValue:(unsigned long long)arg1 forPeer:(id)arg2;
- (void)incrementClockForPeer:(id)arg1;
- (void)increaseClockForPeer:(id)arg1 by:(unsigned long long)arg2;
- (unsigned long long)clockValueForPeer:(id)arg1;
- (id)clockForPeerID:(id)arg1;
- (id)clockForPeer:(id)arg1;
- (_Bool)hasClockForPeerID:(id)arg1;
- (_Bool)hasClockForPeer:(id)arg1;
- (id)initWithJSONRepresentation:(id)arg1;

@end

@interface SYPeer : PBCodable <NSCopying>
{
    NSString *_peerID;
}

@property(retain, nonatomic) NSString *peerID; // @synthesize peerID=_peerID;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)initWithPeerID:(id)arg1;

@end

@interface SYSyncAllObjects : PBCodable <NSCopying>
{
    unsigned long long _version;
    NSMutableArray *_allObjects;
    SYMessageHeader *_header;
    NSString *_syncID;
}

@property(retain, nonatomic) NSMutableArray *allObjects; // @synthesize allObjects=_allObjects;
@property(nonatomic) unsigned long long version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *syncID; // @synthesize syncID=_syncID;
@property(retain, nonatomic) SYMessageHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)allObjectsAtIndex:(unsigned long long)arg1;
- (unsigned long long)allObjectsCount;
- (void)addAllObjects:(id)arg1;
- (void)clearAllObjects;

@end

@interface NSError (SYError)
+ (id)errorWithSYError:(long long)arg1 userInfo:(id)arg2;
- (id)initWithSYError:(long long)arg1 userInfo:(id)arg2;
@end

@interface NSError (NMSError)
@property(readonly, nonatomic, getter=isFromRequest) _Bool fromRequest;
@property(readonly, nonatomic) NSDictionary *persistentUserInfo;
@property(readonly, nonatomic) NSDate *messageSent;
@property(readonly, nonatomic) NSString *idsIdentifier;
@property(readonly, nonatomic) unsigned short messageID;
@end

@interface NSError (FromSYError)
+ (id)errorFromSYErrorInfo:(id)arg1;
@end

