//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/PrivatePlugIns/iPhoneSimulator Build System Support.xcplugin/Contents/MacOS/iPhoneSimulator Build System Support
// UUID: D533BB0C-055C-3911-8B4A-9BA633A42D88
//
//                           Arch: x86_64
//                 Source version: 6760.0.0.0.0
//       Minimum Mac OS X version: 10.9.0
//                    SDK version: 10.10.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @loader_path/../../../../../../PlugIns/Xcode3Core.ideplugin/Contents/Frameworks
//                               = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks
//

@interface XCiPhoneSimulatorCodeSignContext : XCCodeSignContext
{
}

+ (id)codeSignNode:(id)arg1 withMacroExpansionScope:(id)arg2;
+ (id)prepareForCodeSigningWithMacroExpansionScope:(id)arg1 certificateUtilities:(id)arg2;
+ (id)applicableProvisioningProfilePlatform;
+ (BOOL)supportsIOSSigning;
+ (BOOL)supportsMacSigning;
+ (BOOL)supportsDeveloperIDSigning;

@end

