//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreImage.dylib
// UUID: 652EE890-902B-3EA6-8B86-A72CD280FAA5
//
//                           Arch: arm64
//                Current version: 0.0.0
//          Compatibility version: 0.0.0
//                 Source version: 600.0.57.4.0
//            Minimum iOS version: 7.0.0
//                    SDK version: 8.2.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol NSCopying
- (id)copyWithZone:(void *)arg1;
@end

@protocol _TtPSs9AnyObject_
@end

