//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
// UUID: A39B5DB6-9A32-33B6-856B-023900115302
//
//                           Arch: arm64
//                 Source version: 1051.5.14.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//

//
// This file does not contain any Objective-C runtime information.
//
