//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libQLCharts.dylib
// UUID: 6BAA2003-C161-3A2F-AF40-F703F5F59132
//
//                           Arch: x86_64
//                Current version: 222.0.0
//          Compatibility version: 1.0.0
//                 Source version: 222.0.0.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//
// Objective-C Garbage Collection: Unsupported
//

