//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/PrivateFrameworks/CoreFP.framework/Versions/A/CoreFP
// UUID: 408852C0-D98A-3842-8F31-B277E1F8B23B
//
//                           Arch: x86_64
//       Minimum Mac OS X version: 10.6.0
//                    SDK version: 10.7.0
//

//
// This file does not contain any Objective-C runtime information.
//
