//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libAWDProtobufCallHistory.dylib
// UUID: DD7A6E9F-EBA5-3F39-94F9-B0C378CA845B
//
//                           Arch: arm64
//                 Source version: 245.15.0.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//

//
// This file does not contain any Objective-C runtime information.
//
