//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/PrivateFrameworks/AppleGVACore.framework/Versions/A/AppleGVACore
// UUID: 71D3D411-BD9A-302C-AB8C-3A51C4F8CA88
//
//                           Arch: x86_64
//                 Source version: 8.0.10.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.10.0
//

//
// This file does not contain any Objective-C runtime information.
//
