//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/PrivateFrameworks/AirTrafficHost.framework/Versions/A/AirTrafficHost
// UUID: B5C5C75C-C1EA-3A60-BC94-BF2CC5DA2587
//
//                           Arch: x86_64
//       Minimum Mac OS X version: 10.6.0
//                    SDK version: 10.9.0
//
// Objective-C Garbage Collection: Unknown
//

