//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
// UUID: 9A6F789A-B6D6-398A-8BE9-B7E3655B839A
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 235.0.0.0.0
//            Minimum iOS version: 8.2.0
//                    SDK version: 8.2.0
//
// Objective-C Garbage Collection: Unsupported
//

@interface NTKCustomMonogramStore : NSObject
{
    NPSManager *_npsManager;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_notifyClientsOfChange;
- (void)_handlePrefsChanged;
- (void)setCustomMonogram:(id)arg1;
- (id)customMonogram;
- (id)_customMonogramFromPrefs;
- (void)dealloc;
- (id)init;

@end

@interface NTKClockStatusBarSettings : NSObject
{
    NPSManager *_npsManager;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_notifyClientsOfChange;
- (void)_handlePrefsChanged;
- (void)setNotificationsIndicatorEnabled:(_Bool)arg1;
- (_Bool)isNotificationsIndicatorEnabled;
- (void)dealloc;
- (id)init;

@end

@interface NTKMonogram : NSObject
{
}

+ (id)monogram;

@end

@interface NTKCustomWorldCityAbbreviationsStore : NSObject
{
    NPSManager *_npsManager;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_notifyClientsOfChange;
- (void)_handlePrefsChanged;
- (void)setCustomAbbreviation:(id)arg1 forCityIdentifier:(id)arg2;
- (id)customAbbreviations;
- (id)_getCustomAbbreviationsFromPrefs;
- (void)dealloc;
- (id)init;

@end

@interface WorldClockCity (NTKWorldCityAbbreviation)
- (id)_bundleWithAbbreviations;
- (id)_filePathForAbbreviationsResource;
@property(readonly, nonatomic) NSString *abbreviation;
@end

