//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libmecab.1.0.0.dylib
// UUID: B092BD49-854E-3EB5-92A9-B7EBE29C1A7A
//
//                           Arch: x86_64
//                 Source version: 599.9.0.0.0
//       Minimum Mac OS X version: 10.9.0
//                    SDK version: 10.9.0
//

//
// This file does not contain any Objective-C runtime information.
//
